### ISSUE TITLE
Tracking Issue: update go-libp2p to v0.25

### ISSUE THREAD

**Issue by marten-seemann** [filecoin-project/lotus#10199]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [X] lotus client
- [X] lotus JSON-RPC API
- [X] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

The next go-libp2p update will require some more work, since we'll need to completely get rid of the (now deprecated) go-libp2p-core. go-libp2p-core was moved into go-libp2p as part of our mono-repo consolidation effort. Due to subsequent changes made to the core interfaces, `go build` will now fail even if there's _any_ (transitive or non-transitive) dependency on go-libp2p-core.
This means we'll need to update _all_ Lotus dependencies to not use go-libp2p-core any more. This is a painful exercise, but it has to be done once. The good news is that updating go-libp2p in the future will be much easier since as a mono-repo, there are less failure points.

**Updating to v0.25 will be required to build with Go 1.20.**

- [x] https://github.com/filecoin-project/go-fil-markets/pull/777
- [x] https://github.com/ipfs/go-graphsync/pull/401
- [x] https://github.com/ipfs/go-graphsync/pull/403
- [ ] update go-data-transfer to v2 (or cut a v1 minor release that doesn't use go-libp2p-core)
- [ ] update go-legs (depends on graphsync, go-data-transfer)
- [ ] update storetheindex (depends on go-data-transfer)
- [ ] update index-provider (depends on storetheindex)
- [ ] update go-fil-markets (depends on index-provider)
- [x] https://github.com/filecoin-project/dagstore/pull/151
- [x] dagstore v0.6.0: https://github.com/filecoin-project/dagstore/releases/tag/v0.6.0
- [x] https://github.com/ipfs/iptb-plugins/pull/57, release v0.5.0
- [x] https://github.com/ipfs/go-ipfs-http-client/pull/168
- [x] go-ipfs-http-client v0.5.0: https://github.com/ipfs/go-ipfs-http-client/pull/168

This list is not complete yet. I'll add links to PRs here when they are created.

**Comment by rjan90** [comment]
Hey @marten-seemann! Can this issue be closed now as the go-libp2p version is on track to be updated to v0.27.1 (https://github.com/filecoin-project/lotus/pull/10671)?
