### ISSUE TITLE
Unsealing enhancements

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#10316]
> Context: This issue originally started out as `Investigaton of storing tree_r_last in Lotus-Miner` to see how we could make unsealing better, which lead us to a longer path of unsealing enhancements after discussions with the proofs-team. This issue ticket has therefore been repurposed reflect that epic.

**User story:**
As a storage provider (SP) who stores sealed sectors, I need an efficient and reliable unsealing process which does not require manual work to attach workers to where the sealed sector is located, allowing me to focus on handling large volume of sealed sectors being unsealed for clients.

**Acceptence criteria:**

- Unsealing of every sector type (Deals, SnapDeal) functions without bugs.
- The unsealing process should not require manual intervention for unsealing to work on unsealing-workers; such as attaching the location where the sealed sector is stored to a worker.

**Techincal scope**

```[tasklist]
### Tasks
- [x] Investigate storing tree_r_last in Lotus-Miner
- [x] https://github.com/filecoin-project/lotus/pull/10639
- [x] https://github.com/filecoin-project/lotus/pull/10626
- [ ] https://github.com/filecoin-project/lotus/pull/10913
- [ ] https://github.com/filecoin-project/rust-fil-proofs/issues/1666
- [ ] https://github.com/filecoin-project/rust-fil-proofs/issues/1665
- [ ] https://github.com/filecoin-project/rust-fil-proofs/issues/1667
- [ ] https://github.com/filecoin-project/lotus/issues/10994
- [ ] [“Split PC1” for unsealing](https://www.notion.so/pl-strflt/Improved-APIs-for-Lotus-9bd4fa443e254701a081f51ad301fddf?pvs=4#5d0a9b5961044021a99ada745282e114).
```

**Point estimation:**

**Comment by rjan90** [comment]
Now that we have new APIs from the proofs team 💙:

```[tasklist]
- [ ] Implement the new [SnapDeals decodes API](https://www.notion.so/pl-strflt/Improved-APIs-for-Lotus-9bd4fa443e254701a081f51ad301fddf?pvs=4#a9ae8b0522f644528a8185561d97631c) to fix unsealing of SnapDeals.
- [ ] Work on the [“Split PC1” for unsealing](https://www.notion.so/pl-strflt/Improved-APIs-for-Lotus-9bd4fa443e254701a081f51ad301fddf?pvs=4#5d0a9b5961044021a99ada745282e114) to allow for Unsealing to be computed without moving sealed sector to an unseal worker.
```

**Comment by rjan90** [comment]
Closing this issue now that https://github.com/filecoin-project/lotus/pull/11011 has been merged, and is on its way to users with the Lotus v1.23.4 release train.

The linked PR introduces significant improvements and bugfixes with regards to unsealing, and ensures that unsealing operates as anticipated. Consequently, the unsealing of deal sectors, Snap-sectors without sector keys, and Snap-sectors with sector keys now all function seamlessly.

Additional improvements/bugfixes with this PR includes:
- Enabling unsealing on workers with only sealing paths. :tada:
- Transferring unsealed files to long-term storage upon successful unsealing. :arrow_right:
- Ensuring no residual files in sealing paths post a successful unsealing operation. :broom:

One area to explore further is if want to spend additional time splitting the "PC1-step" (TreeD building and SDR) in the unsealing pipeline. See the `More efficient deal data pipeline` section in https://pl-strflt.notion.site/Improved-APIs-for-Lotus-9bd4fa443e254701a081f51ad301fddf.
