### ISSUE TITLE
`Lotus-Miner` Backlog Sprint

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#10338]
> **Note**
> This is a project issue, and the work items are subject to changes and refinements.

## Goal
Address and fix outstanding storage provider issues that cause operational instability and excessive time to debug and fix, with a high priority on critical operations (PoSt-operations), and enhancements in unsealing.

## Work Items

```[tasklist]
### Completed items - Targeted for v1.21.0
- [ ] https://github.com/filecoin-project/lotus/issues/9407
- [ ] https://github.com/filecoin-project/lotus/issues/8566#issuecomment-1248571522
- [ ] https://github.com/filecoin-project/lotus/issues/9074
- [ ] https://github.com/filecoin-project/lotus/issues/7866
- [ ] https://github.com/filecoin-project/lotus/issues/10210
- [ ] https://github.com/filecoin-project/lotus/issues/10362
- [ ] https://github.com/filecoin-project/lotus/issues/8362#issuecomment-1261053300
- [ ] https://github.com/filecoin-project/lotus/issues/9854
- [ ] https://github.com/filecoin-project/lotus/issues/8561
- [ ] https://github.com/filecoin-project/lotus/issues/9968
```

```[tasklist]
### Targeted for later releases
- [ ] #10337
- [ ] https://github.com/filecoin-project/lotus/issues/10262
- [ ] https://github.com/filecoin-project/lotus/issues/5436
```

**Comment by rjan90** [comment]
Closing this, this sprint completed earlier in the year
