### ISSUE TITLE
Lotus v1.20.0 final checklist

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#10347]
- [x] Land https://github.com/filecoin-project/lotus/pull/10333
- [x] nice to land https://github.com/filecoin-project/lotus/pull/10344
- [x] Update go-state-types here in Lotus to v0.10.0: https://github.com/filecoin-project/lotus/pull/10359
- [x] https://github.com/filecoin-project/lotus/pull/10358
- [x] really nice to have https://github.com/filecoin-project/lotus/issues/10348
- [x] FFI:
  - [x] Land https://github.com/filecoin-project/filecoin-ffi/pull/374
  - [x] cut an FFI release
  - [x]  merge FFI `release/lotus-v1.20.0` into master: https://github.com/filecoin-project/filecoin-ffi/pull/376
  - [x] Update FFI here in Lotus to the release cut: https://github.com/filecoin-project/lotus/pull/10360
- [x] Actors:
  - [x] Update all FVM deps to 3.0.0 (final releases)
  - [x] Land https://github.com/helix-onchain/filecoin/pull/200
  - [x] Publish Helix crates with ^
  - [x] Update helix deps to final releases in actors
  - [x] Publish v10.0.0
  - [x] Update actors bundle in Lotus to the published release
- [ ] Bump Lotus version
- [ ] @jennijuju Changelog
- [ ] SHIP
- [ ] Merge `releases` back into `master` (the usual release steps)

**Comment by rjan90** [comment]
Closing this issue since all the steps have been completed 🚀
