### ISSUE TITLE
Epic: Message Index

### ISSUE THREAD

**Issue by vyzo** [filecoin-project/lotus#10536]
# The Message Index epic

See https://github.com/filecoin-project/lotus/issues/10326 for background.

PR https://github.com/filecoin-project/lotus/pull/10452 introduces an MVP of a on-disk MessageIndex, intended to accelerate calls like `StateSearchMessage`.
It is a functional minimal solution, and we expect to follow up with several improvements.
This issue collects follow up considerations for easy reference.

## TODOs
- [ ] https://github.com/filecoin-project/lotus/issues/10663 (This could arguably be the biggest win, as it will allow us to accelerate chain store calls)
- [x] #10583
- [x] #10537
- [ ] (maybe) Consider populating the index when first creating the db and on startup reconciliation; this is strictly speaking not necessary with snapshot population and the shed tools, but it could be nice to have.
- [ ] (maybe) Consider using the event observer; note that this may not be necessary and in fact, when we move the index inside the chain store possibly counter productive.
- [ ] #10589
- [ ] #10600
- [ ] (nice to have) automatically delete corrupt databases when detected

**Comment by maciejwitowski** [comment]
From Slack: @vyzo said it makes sense to do "Make the index owned and used by the chain store", and then more to horizontal scaling work.

**Comment by BlocksOnAChain** [comment]
@fridrik01 Is still something we plan to pursue and add to our work scope, before we move towards foundational work?

**Comment by fridrik01** [comment]
I think we could close this issue. Related to this, an important feature would be for lotus to be able to automatically handle backfilling of the msgindex and the other sqlite databases (events/txhash). I created a issue for that https://github.com/filecoin-project/lotus/issues/11007 and added it to the vertical scaling workstream

**Comment by BlocksOnAChain** [comment]
sounds good to me. @Stebalien ok with you to close?
