### ISSUE TITLE
[EPIC] Lotus Profiling 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#10888]
Lotus profiling ideas proposed by @arajasek 

```[tasklist]
- [ ] memory consumption profiling 
- [ ] DB dize profiling 
- [ ] Mining profiling 
- [ ] message execution profiling
```

**Comment by jennijuju** [comment]
@arajasek to make sure we have the maximum impact on this effort - I think our end goal would be something like https://github.com/filecoin-project/boost/tree/main/docker/monitoring. where we launch a monitoring board easily with any node we have, and get stats on how things are changing over time, or when we have a new release and so on. wdyt?

**Comment by jennijuju** [comment]
some ideas https://geth.ethereum.org/docs/monitoring/dashboards

**Comment by mur-me** [comment]
Speaking about dashboards, we already have dashboards built for our RPC use-cases.
Additionally lotus team created few new dashboards to monitor consequences of the Pi Day.

Probably, this dashboards could be a good starting point or contribute in the common goal.

Link: https://grafana.com/orgs/openworklabbot/dashboards

Fill free to ping Glif team for details
