### ISSUE TITLE
Supranational brownfield C2 <> Lotus-Miner

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#10976]
Tracking issue for implementing [Supranationals brownfield C2](https://github.com/supranational/supra_seal/tree/main/c2) as a drop-in replacement for the current C2 sealing proof in Lotus-Miner.

**User story:**
As a storage provider (SP) I want to utilize the highly optimized brownfield C2 sealing primitives from SupraNational, so that I can experience reduced energy consumption and hardware needs while achieving significant improvements in sealing times for the C2 tasks without compromising compatibility with deal-sectors, CC-sectors or sector sizes applicable on the Filecoin mainnet.

**Acceptence criteria:**
- Must be usable with both 32 GiB and 64 GiB sector sizes
- Must be usable with both deal- and CC-sectors
- The integration should be available behind a `cuda-supraseal` flag when building the C2-worker for reduced risk initially.

**Techincal Scope**

```[tasklist]
### Task list
- [x] Final rust crates from SupraNational published
- [ ] https://github.com/filecoin-project/bellperson/pull/308
- [ ] https://github.com/filecoin-project/rust-fil-proofs/pull/1709
- [ ] https://github.com/filecoin-project/rust-filecoin-proofs-api/pull/90
- [x] Cut new proofs release
- [x] Testing plan for the Supranational brownfield C2 <> Lotus-Miner. https://www.notion.so/pl-strflt/Testing-plan-Supranational-brownfield-C2-Lotus-Miner-60641eeac59448499be8c59bbf935040?pvs=4
- [ ] https://github.com/filecoin-project/lotus-docs/issues/598
- [x] Rollout of Supranational brownfield C2 - Coming in Lotus v1.25.0 behind a feature flag
```

**Benchmarks/estimated improvements with 32GiB sectors:**

**Singe GPU (Quadro RTX 6000):**
_Supranational brownfield C2 benchmark:_
```
2023-05-24T09:39:01.087 INFO bellperson::groth16::prover > synthesis time: 79.801428953s
2023-05-24T09:39:01.087 INFO bellperson::groth16::prover > starting proof timer
2023-05-24T09:41:22.308 INFO bellperson::groth16::prover > prover time: 141.220403529s
```

_Current C2 proof  benchmark:_

```
2023-05-24T09:44:22.924 INFO bellperson::groth16::prover > synthesis time: 79.539678257s
2023-05-24T09:44:22.925 INFO bellperson::groth16::prover > starting proof timer
2023-05-24T10:00:29.467 INFO bellperson::groth16::prover > prover time: 966.542747351s
```

**4 GPUs (Quadro RTX 6000):**
_Supranational brownfield C2 benchmark:_
```
2023-05-24T09:12:17.867 INFO bellperson::groth16::prover > synthesis time: 81.67488431s
2023-05-24T09:12:17.867 INFO bellperson::groth16::prover > starting proof timer
2023-05-24T09:13:10.361 INFO bellperson::groth16::prover > prover time: 52.494216036s
```

_Current C2 proof benchmark:_
```
2023-05-24T09:26:06.753 INFO bellperson::groth16::prover > synthesis time: 79.765751616s
2023-05-24T09:26:06.753 INFO bellperson::groth16::prover > starting proof timer
2023-05-24T09:34:46.581 INFO bellperson::groth16::prover > prover time: 519.828223593s
```

**Comment by vmx** [comment]
> * The integration should be available behind a `supraseal` flag when building for reduced risk initially.

The filcrypto team decided to name this flag in our code base `cuda-supraseal`, to make clear that it works only on CUDA. You might want to do the same. Also it will then use CUDA for the other (non C2) parts.

**Comment by rjan90** [comment]
Closing now that SupraSeal C2 is in Lotus v1.25.0-rc1
