### ISSUE TITLE
High availability of WindowPoSt

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#10991]
> WIP tracking issue for HA of WindowPoSt

**User Story:**
- As a storage provider (SP) I need a high availability solution for windowPoSt to ensure that I don't miss any proving deadlines, scheduling, computations and submissions. This will allow me to maintain and maximize the reliability of my services, and not lose block rewards or get slashed due to unnecessary failed proving deadlines.

**Acceptance Criteria:**
- The system should allow for disruption-free proving during Lotus-Miner restarts.
- The system should know if a deadline/partition already has been proven, to prevent redoing a WindowPoSt computation at restarts.
- The proving process should skip sectors if its is unable to read their required files, instead of failing the whole proving deadline.

**Technical Scope**

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/lotus/issues/10379
- [ ] https://github.com/filecoin-project/lotus/issues/11024
- [ ] https://github.com/filecoin-project/lotus/issues/11025
- [ ] https://github.com/filecoin-project/lotus/issues/11026
- [ ] https://github.com/filecoin-project/lotus/issues/11106
- [ ] https://github.com/filecoin-project/lotus/issues/11112
- [ ] https://github.com/filecoin-project/lotus/issues/11113
- [ ] https://github.com/filecoin-project/lotus/issues/11170
- [ ] https://github.com/filecoin-project/lotus/issues/11172
- [ ] https://github.com/filecoin-project/lotus/issues/11174
```

**Comment by snadrus** [comment]
This is resolved by the lotus-provider binary.
