### ISSUE TITLE
Implement new SnapDeals decodes API for unsealing

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#10994]
We want to implement the new SnapDeals decodes API to reliably and efficiently be able to unseal SnapDeal sectors. Documentation for the [new improved proofs APIs can be found here](https://www.notion.so/pl-strflt/Improved-APIs-for-Lotus-9bd4fa443e254701a081f51ad301fddf?pvs=4#a9ae8b0522f644528a8185561d97631c)

**Acceptence criteria**
- The new SnapDeals decodes API should be successfully integrated into the existing unsealing system
- The system should handle any errors returned by the SnapDeals decodes API gracefully and log them for troubleshooting
- SnapDeals unsealing should work 100% of the time
- SnapDeals unsealing shouldn't leave files behind on workers

```[tasklist]
### tasks
- [x] Proofs API review/plumbing
- [x] Add integration test
- [x] Test unsealing of a SnapDeal sector
```
