### ISSUE TITLE
SP loses connection to workers and scheduler freaks out, closes wdpost processing.

### ISSUE THREAD

**Issue by duanbnz** [filecoin-project/lotus#11021]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon: lotus version 1.23.0+mainnet+git.d1d4b35ad
SP: lotus-miner version 1.23.0+mainnet+git.d1d4b35ad
```

### Repro Steps

Have not been able to reproduce this.

### Describe the Bug

SP lost connection to workers, possibly due to heavy load  - made the scheduler freak out and closes wdpost processing

### Logging Information

```text
2022-06-16T05:52:26.354-0400	WARN	advmgr	sector-storage/sched_worker.go:209	failed to check worker session	{"error": "RPC client error: sendRequest failed: Post \"http://XX.X.X.XX:XXXX/rpc/v0\\": context deadline exceeded"}
2022-06-16T05:52:29.058-0400	WARN	advmgr	sector-storage/sched_worker.go:209	failed to check worker session	{"error": "RPC client error: sendRequest failed: Post \"http://XX.X.X.XX:XXXX/rpc/v0\\": context deadline exceeded"}
2022-06-16T05:52:36.354-0400	WARN	advmgr	sector-storage/sched_worker.go:209	failed to check worker session	{"error": "RPC client error: sendRequest failed: Post \"http://XX.X.X.XX:XXXX/rpc/v0\\": context deadline exceeded"}
2022-06-16T05:53:38.903-0400	WARN	advmgr	sector-storage/sched_worker.go:209	failed to check worker session	{"error": "RPC client error: sendRequest failed: Post \"http://XX.X.X.XX:XXXX/rpc/v0\\": context deadline exceeded"}
2022-06-16T05:53:38.903-0400	ERROR	storageminer	storage/wdpost_sched.go:181	handling head updates in window post sched: handler: websocket connection closed
2022-06-16T05:53:38.903-0400	WARN	storageminer	storage/wdpost_sched.go:124	window post scheduler notifs channel closed
```

```[tasklist]
### Tasks
```

**Comment by duanbnz** [comment]
In another instance on the same SP, the scheduler got stuck and just stopped producing new sectors:

Scheduler stuck, no new sectors after this one:

2023-06-19T23:56:30.943-0400    INFO    sectors pipeline/input.go:308   Adding piece for deal 42240059 (publish msg: bafy2bzacebwmr5bq575kpgyd56g7y2ldsmvxkre6vgneeolxfnhadqroy7nkg)

**Comment by TippyFlitsUK** [comment]
What spec is the system you are seeing this on @duanbnz?

**Comment by duanbnz** [comment]
> What spec is the system you are seeing this on @duanbnz?

@TippyFlitsUK, apolgies for the delay, let me know if you need anything else:

CPU

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7F72 24-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1745.203
CPU max MHz:                     3200.0000
CPU min MHz:                     2500.0000

Memory:
				total       used        free      	shared  	buff/cache   	available
Mem:           	1.5Ti       216Gi       360Gi       63Mi       	934Gi       	1.3Ti
Swap:             0B          0B          0B

GPU:
3:00.0 VGA compatible controller: NVIDIA Corporation TU102GL [Quadro RTX 6000/8000] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: NVIDIA Corporation Quadro RTX 6000
c3:00.0 VGA compatible controller: NVIDIA Corporation TU102GL [Quadro RTX 6000/8000] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: NVIDIA Corporation Quadro RTX 6000

**Comment by TippyFlitsUK** [comment]
What kind of load were you under when this happened @duanbnz? 
It would also be very useful if you could please attach your logs to this thread. 🙏

**Comment by duanbnz** [comment]
Will send logs shortly - load was nothing out of the norm where the server was overloaded at any point in time, let me know what stats you wanna see and I will gladly post them for you as we actively mine on this server.

**Comment by duanbnz** [comment]
My apologies but seems that log is gone - closing this ticket

**Comment by TippyFlitsUK** [comment]
No worries @duanbnz 

Let us know if it happens again and we can re-open! 🙏

**Comment by duanbnz** [comment]
Issue  was not resolved, unfortunately lost the logs  @daveyhook, will relog issue with fresh logs when it happens again
