### ISSUE TITLE
curl -I https://snapshots.mainnet.filops.net/minimal/latest can't download check Plz

### ISSUE THREAD

**Issue by enginkorkmaaz** [filecoin-project/lotus#11494]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
aria2c -x5 https://snapshots.mainnet.filops.net/minimal/latest.zst

06/30 05:51:48 [NOTICE] Downloading 1 item(s)

06/30 05:51:49 [NOTICE] CUID#7 - Redirecting to https://snapshots.mainnet.filops.net/minimal/latest
[#c6c78d 0B/0B CN:1 DL:0B]
06/30 05:51:49 [NOTICE] CUID#7 - Redirecting to https://pub-fd31751bcb69400eb39e694385c19457.r2.dev/minimal/2993040_2023_06_30T04_00_00Z.car.zst

06/30 05:51:49 [NOTICE] CUID#7 - Redirecting to https://snapshots.mainnet.filops.net/minimal/latest

06/30 05:51:50 [NOTICE] CUID#7 - Redirecting to https://pub-fd31751bcb69400eb39e694385c19457.r2.dev/minimal/2993040_2023_06_30T04_00_00Z.car.zst

06/30 05:51:50 [NOTICE] CUID#7 - Redirecting to https://snapshots.mainnet.filops.net/minimal/latest
[#c6c78d 0B/0B CN:1 DL:0B]
06/30 05:51:50 [NOTICE] CUID#7 - Redirecting to https://pub-fd31751bcb69400eb39e694385c19457.r2.dev/minimal/2993040_2023_06_30T04_00_00Z.car.zst

06/30 05:51:50 [NOTICE] CUID#7 - Redirecting to https://snapshots.mainnet.filops.net/minimal/latest

06/30 05:51:51 [NOTICE] CUID#7 - Redirecting to https://pub-fd31751bcb69400eb39e694385c19457.r2.dev/minimal/2993040_2023_06_30T04_00_00Z.car.zst

06/30 05:51:51 [NOTICE] CUID#7 - Redirecting to https://snapshots.mainnet.filops.net/minimal/latest
[#c6c78d 0B/0B CN:1 DL:0B]
06/30 05:51:51 [NOTICE] CUID#7 - Redirecting to https://pub-fd31751bcb69400eb39e694385c19457.r2.dev/minimal/2993040_2023_06_30T04_00_00Z.car.zst

06/30 05:51:51 [ERROR] CUID#7 - Download aborted. URI=https://snapshots.mainnet.filops.net/minimal/latest.zst
Exception: [AbstractCommand.cc:856] errorCode=1 Failed to establish connection, cause: Connection refused

06/30 05:51:51 [NOTICE] Download GID#c6c78df0e2fa4b39 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
c6c78d|ERR |       0B/s|https://snapshots.mainnet.filops.net/minimal/latest.zst

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
```

### Repro Steps

curl -I https://snapshots.mainnet.filops.net/minimal/latest

### Describe the Bug

curl -I https://snapshots.mainnet.filops.net/minimal/latest can't download check Plz
aria2c -x5 https://snapshots.mainnet.filops.net/minimal/latest.zst
same problem.

### Logging Information

```text
aria2c -x5 https://snapshots.mainnet.filops.net/minimal/latest.zst

06/30 05:51:48 [NOTICE] Downloading 1 item(s)

06/30 05:51:49 [NOTICE] CUID#7 - Redirecting to https://snapshots.mainnet.filops.net/minimal/latest
[#c6c78d 0B/0B CN:1 DL:0B]
06/30 05:51:49 [NOTICE] CUID#7 - Redirecting to https://pub-fd31751bcb69400eb39e694385c19457.r2.dev/minimal/2993040_2023_06_30T04_00_00Z.car.zst

06/30 05:51:49 [NOTICE] CUID#7 - Redirecting to https://snapshots.mainnet.filops.net/minimal/latest

06/30 05:51:50 [NOTICE] CUID#7 - Redirecting to https://pub-fd31751bcb69400eb39e694385c19457.r2.dev/minimal/2993040_2023_06_30T04_00_00Z.car.zst

06/30 05:51:50 [NOTICE] CUID#7 - Redirecting to https://snapshots.mainnet.filops.net/minimal/latest
[#c6c78d 0B/0B CN:1 DL:0B]
06/30 05:51:50 [NOTICE] CUID#7 - Redirecting to https://pub-fd31751bcb69400eb39e694385c19457.r2.dev/minimal/2993040_2023_06_30T04_00_00Z.car.zst

06/30 05:51:50 [NOTICE] CUID#7 - Redirecting to https://snapshots.mainnet.filops.net/minimal/latest

06/30 05:51:51 [NOTICE] CUID#7 - Redirecting to https://pub-fd31751bcb69400eb39e694385c19457.r2.dev/minimal/2993040_2023_06_30T04_00_00Z.car.zst

06/30 05:51:51 [NOTICE] CUID#7 - Redirecting to https://snapshots.mainnet.filops.net/minimal/latest
[#c6c78d 0B/0B CN:1 DL:0B]
06/30 05:51:51 [NOTICE] CUID#7 - Redirecting to https://pub-fd31751bcb69400eb39e694385c19457.r2.dev/minimal/2993040_2023_06_30T04_00_00Z.car.zst

06/30 05:51:51 [ERROR] CUID#7 - Download aborted. URI=https://snapshots.mainnet.filops.net/minimal/latest.zst
Exception: [AbstractCommand.cc:856] errorCode=1 Failed to establish connection, cause: Connection refused

06/30 05:51:51 [NOTICE] Download GID#c6c78df0e2fa4b39 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
c6c78d|ERR |       0B/s|https://snapshots.mainnet.filops.net/minimal/latest.zst

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
```

```[tasklist]
### Tasks
```

**Comment by enginkorkmaaz** [comment]
![WhatsApp Image 2023-12-07 at 04 08 16](https://github.com/filecoin-project/lotus/assets/152744539/448c5a0a-2966-41dc-a6f1-15ba96e71e5c)

**Comment by beck-8** [comment]
you can replace dns or add proxy

**Comment by rjan90** [comment]
As noted by @beck-8 replacing dns should solve the issues you are facing here. You can also try to download a snapshot from the https://forest-archive.chainsafe.dev/latest/mainnet/
