### ISSUE TITLE
[WIP] Lotus nv22 integration and testing 

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#11584]
We are preparing to ship Filecoin nv22 on April 2nd. Check the [NV22 logistics track board](https://github.com/orgs/filecoin-project/projects/104/views/4) for other key dates.

In order to prepare for the first Lotus v1.26.0-rc, we need to:

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/lotus/issues/11593
- [x] Reset butterfly network to nv21, have it upgrade to nv22, and perform basic testing
- [x] Land outstanding items for accepted FIPs in Built-In actors/FVM
- [x] [ ] Redo the Butterfly testnet reset with final code
- [x] Cut RCs for the FVM and built-in actors
- [x] [ ] Package it all in Lotus
```

**Comment by rjan90** [comment]
### Testing plan: Switch Drand to Quicknet

**Comment by rjan90** [comment]
### Testing plan: Remove cron-based automatic deal settlement

**Comment by rjan90** [comment]
### Testing plan: Direct Data Onboarding

**Comment by rjan90** [comment]
### Testing plan: Add built-in Actor events in the Verified Registry, Miner and Market Actors

**Comment by Reiers** [comment]
### Testing plan: DDO - Direct Data Onboarding


**General**
- [ ] Daemon stays in sync
- [ ] Onboard a regular deal sector via Boost check that events gets emitted.
- [ ] Onboard a FIL+ sector via Boost check that events gets emitted.
- [ ] Snap up a sector, and check that events gets emitted.

**Events for miner:**

- [ ] Sector update (SnapDeals / ProveCommit)
- [ ] Sector update batching (ProveReplicaUpdates3)
- [ ] Sector activation 

**Events for market:**

- [ ] Deal published 
- [ ] Deal activated

**Comment by magik6k** [comment]
DDO Integration tests
- [ ] Test a sector with Fil+ DDO piece
- [ ] Test a sector with a (fil+) DDO piece + custom market actor??
- [ ] Test the above with a piece filling half of a sector, and CC padding
- [ ] Test the above with two pieces and inter-piece padding (p1-PP-p2-p2)
- [ ] Test the above with snapdeals sector

**Comment by jennijuju** [comment]
@Reiers 
we will cover event testing including the DDO case!

**Comment by jennijuju** [comment]
@magik6k @Reiers a couple DDO things to test and confirm

- [ ] one f05 and one DDO data ends up in the same sector, and the f05 deal can be found in f05 state and is fully activated 
- [ ] one can aggregate multiple DDO sectors 
- [ ] test a sector with multiple DDO pieces 
- [ ] test a sector with multiple DDO pieces, some with data cap and some without 
- [ ] test a couple fil+ deals (non f05) arriving at a similar time to lotus miner, one has a allocation duration of 180days and the other has 3.5 years 
- [ ] same as above but using snap
- [ ] the existing deal making pathway still works

**Comment by celernetworkcoloros** [comment]
: patch
