### ISSUE TITLE
Benchmark the nv22/DDO-migration

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#11593]
With an eye on the nv22 migration we need to land the migration-integration and run benchmarks on the nv22 DDO-migration.

### Performance
The migration should run in < 1 min for SPs with good hardware, < 5 mins for most users, and < 2 hours for all cases (including archival nodes). Additionally, the node's memory usage during the migration period should not cause the node to fall out of sync.

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/go-state-types/pull/234
- [ ] https://github.com/filecoin-project/go-state-types/pull/236
- [x] Hook up the migration into the[ lotus-shed, benchmark tool.](https://github.com/filecoin-project/lotus/blob/master/cmd/lotus-shed/migrations.go)
- [x] [Run migration benchmark. Confirm performance is within acceptable range](https://lotus.filecoin.io/kb/test-migration/)
```

**Comment by rjan90** [comment]
Some migration benchmarks landing in the comments of the PR. Posting links here for visibility:

- https://github.com/filecoin-project/lotus/pull/11601#issuecomment-1914725492
- https://github.com/filecoin-project/lotus/pull/11601#issuecomment-1914737315

**Comment by rjan90** [comment]
Closed by: https://github.com/filecoin-project/lotus/pull/11601#issuecomment-2011378071.

Migration time is consistently under one epoch now
