### ISSUE TITLE
[Epic] Curio Beta

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/lotus#11754]
This is the parent tracking issue related to the shipping Curio to beta testers.

# Problem Statement
To get Curio out the door we are working in parallel on multiple work stream. This makes it very hard to prioritise the work and track it. This issue is meant to help prioritise the pending work for Curio beta and create tracking issues for it.

- [ ] #11755
- [x] #11756
- [x] #11757
- [x] [SPTool actor management cli tool](https://github.com/filecoin-project/lotus/issues/11733)
- [x] #11791
- [x] #11758
- [x] #11759
- [x] [Refactor Curio graceful shutdown](https://github.com/filecoin-project/lotus/pull/11794)
- [x] [Create Curio documentation](https://github.com/filecoin-project/lotus-docs/pull/714)
- [x] storage reservations in SDRTrees / MoveStorage
- [x] [Split SDRTrees into prefetch and compute](https://github.com/filecoin-project/lotus/pull/11895)
- [x] [Curio web for sector info](https://github.com/filecoin-project/lotus/pull/11869)
- [x] Support NV22: Curio DDO
- [x] Finish Curio website
- [x] [Miner ID based storage filter](https://github.com/filecoin-project/lotus/pull/11801)
- [x] Migration and config should add miner IDs to base layer
- [ ] Unsealing
- [x] https://github.com/filecoin-project/lotus/issues/11797
- [x] Switch to YB Postgres drivers

**Comment by LexLuthr** [comment]
TODOs after pre-beta:

- [ ] more than 1 deal per sector
- [ ] snap deals
- [ ] UI
- [ ] precommit/commit batching
- [ ] Can accept extension
- [ ] Curio Market
- [ ] Storage cleanup
- [ ] Sealed sector storage by deadline

**Comment by snadrus** [comment]
> TODOs after pre-beta:
When we determine which items are needed for Curio-production, lets link that epic here.

**Comment by LexLuthr** [comment]
Missing methods in Forest to make Curio work with Forest:

			ChainTipSetWeight
			MinerCreateBlock
			MpoolSelect
			StateGetBeaconEntry
			StateMinerInitialPledgeCollateral
			StateMinerPartitions
			StateMinerPreCommitDepositForPower
			StateMinerSectors
			StateSectorPreCommitInfo
			SyncSubmitBlock

**Comment by LexLuthr** [comment]
Closing this as we are now close to GA.
