### ISSUE TITLE
[Replaced] Lotus nv23 integration and testing

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#11939]
## 2024-06-27 Update
This is is being closed because it has been replaced by:
1. More encompassing network upgrade tracking document: https://docs.google.com/document/d/11jN9E4IcgcbU_6acAIHuh29v7yGFj7OHiiGYpoUuSEs/edit 
2. More detailed issues around things like the Lotus release: https://github.com/filecoin-project/lotus/issues/12109
The testing plans in this document have been copied out to the network upgrade tracking document.

---
This tracks the Lotus portion of the wider multi-repo/party nv23 effort that is being tracked in https://github.com/orgs/filecoin-project/projects/118.  See that board's "logistics timeline" view for the most accurate dates.

Lotus nv23 integration and testing items:

```[tasklist]
### Tasks
- [ ] #11772
- [x] Add testing plans for FIPs targeting nv23
- [x] Land outstanding items for accepted FIPs in Built-In actors/FVM
- [x] RC for https://github.com/filecoin-project/builtin-actors/issues/1551
- [ ] https://github.com/filecoin-project/lotus/issues/12121
- [ ] https://github.com/filecoin-project/lotus/issues/12109
- [ ] Redo the Butterfly testnet reset with final code per https://github.com/filecoin-project/lotus-infra/blob/master/Reset_Butterfly_Network.md
- [ ] https://github.com/filecoin-project/lotus/issues/12128
```

There is a separate [issue for the corresponding v1.28.0 release](https://github.com/filecoin-project/lotus/issues/12109).

**Comment by aarshkshah1992** [comment]
Testplan for https://github.com/filecoin-project/lotus/pull/11930

- Submit a signed legacy ETH transaction to transfer FIL from account A to account B and confirm the transfer on chain
- Submit a signed legacy ETH transaction to deploy an ERC-20 contract on Filecoin
- Invoke a signed legacy ETH token transfer transaction on the above contract and ensure the balances are updated on chain

**Comment by rjan90** [comment]
Testplan for FIP-0085:

- [ ] Migration test in lotus asserting the new state of f090.
- [ ] In a devnet setup f090 with a known key and spend some money before the network upgrade. Demonstrate that this does not work after migration.

**Comment by rjan90** [comment]
Testing plan for FIP-0090: Non-Interactive PoRep: https://github.com/filecoin-project/builtin-actors/issues/1534#issuecomment-2072708557

**Comment by ZenGround0** [comment]
Testing plan for FIP-0065
- [x] itest demonstrating locked supply does not include f05 balance in nv23
- [ ] Devnet test 
1. Setup devnet node to run nv22 and then migrate to nv23
2. Make some very expensive deals to set the market locked balance high.  Check f05 locked balance to get an exact number of locked FIL.
3. A few epochs before migration record external circulating supply (`lotus state circulating-supply`) and internal approximate circulating supply (no CLI command need to query API `StateVMCirculatingSupplyInternal`) 
4. After migration do the same 
5. Compare the circulating supply values and sanity check that they are roughly different by locked market balance.  This will only be approximate because circulating supply in devenet is always fluctuating anyway.

**Comment by BigLep** [comment]
Items I will do when I become part of lotus-contributors (if it doesn't get done sooner):
1. Pin the issue
2. Add it to https://github.com/orgs/filecoin-project/projects/118
3. Make a note in the issue description that "this tracks the Lotus portion of the wider multi-repo/party nv23 effort that is being tracked in https://github.com/orgs/filecoin-project/projects/118"

**Comment by rjan90** [comment]
## Butterfly-Network testing

**Branch:** https://github.com/filecoin-project/lotus/tree/phi/nv23-butterfly-testing
- This branch is based on the latests final Lotus release (Lotus v1.27.0) with only the network consensus breaking changes applied to it.

## Testingplan

Coming

**Comment by BigLep** [comment]
This is is being closed because it has been replaced by:
1. More encompassing network upgrade tracking document: https://docs.google.com/document/d/11jN9E4IcgcbU_6acAIHuh29v7yGFj7OHiiGYpoUuSEs/edit 
2. More detailed issues around things like the Lotus release: https://github.com/filecoin-project/lotus/issues/12109
The testing plans in this document have been copied out to the network upgrade tracking document.

**Comment by BigLep** [comment]
Reopening until I get https://docs.google.com/document/d/11jN9E4IcgcbU_6acAIHuh29v7yGFj7OHiiGYpoUuSEs/edit made publicly viewable.

**Comment by rjan90** [comment]
Closing and unpinning this issue now that https://docs.google.com/document/d/11jN9E4IcgcbU_6acAIHuh29v7yGFj7OHiiGYpoUuSEs has been made publicly viewavle.
