### ISSUE TITLE
Tracking Issue: Flaky Tests in GitHub Actions

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#12001]
## Description

This tracking issue is to monitor the investigation and resolution of flaky/failing tests observed only in GitHub Actions. These tests have shown at most 2 failures in 54 runs. (Ref: #11786)

## List of Flaky Tests

```[tasklist]
### Tasks
- [ ] `itest-path_type_filters`
- [ ] `itest-eth_filter`
- [ ] `itest-wdpost`
- [ ] `itest-deals_pricing`
- [ ] `itest-sector_finalize_early`
- [ ] `itest-wdpost_worker_config`
- [ ] `itest-cli`
- [ ] `multicore-sdr`
- [ ] `itest-harmonydb`
```

**Comment by jennijuju** [comment]
@aarshkshah1992 with your remove market PR, will itest-deals_pricing be gone as well?

**Comment by rjan90** [comment]
Some additional notes on a couple of these tests:

- `itest-harmonydb` can probably be removed once Curio has migrated succesfully to their own repo.
- `multicore-sdr` in the [PR adding it](https://github.com/filecoin-project/lotus/pull/6479) it was noted that `"the test works when run individually, but broken when it runs with any other tests as proofs expect the call to FilInitLogFd to be the very first proofs call."`
- `itest-sector_finalize_early` tests finalizing a sector (i.e moving it to the long-term storage), before the ProveCommit-message is sent. The option/config was added iirc, because there where a lot of issues early on that could cause the FinalizeStep (moving a sealed sector to its LTS) to fail, that raised the want for this config. But afaict, the finalize early config is not set by default today.

**Comment by rjan90** [comment]
With the removal of markets in Lotus/Lotus-Miner, these tests has been removed:
- `itest-path_type_filters`
- `itest-deals_pricing`

Ref: https://github.com/filecoin-project/lotus/pull/12099

**Comment by aarshkshah1992** [comment]
Fixed a couple of flaky tests as part of 

https://github.com/filecoin-project/lotus/pull/12203 [eth_filters_itest]
https://github.com/filecoin-project/lotus/pull/12200 [eth_legacy_transaction_itest]

**Comment by aarshkshah1992** [comment]
https://github.com/filecoin-project/lotus/actions/runs/9887807887/job/27310358031?pr=12207

NI-PoRep itest

**Comment by rvagg** [comment]
This one's new, `unit-rest`: https://github.com/filecoin-project/lotus/actions/runs/9950234508/job/27487773104?pr=12229#logs

Not sure I want to register this as a high priority flaky because it's the first time I've seen it and I can't even see in the output what the failure is because so many tests are mixed up.

**Comment by aarshkshah1992** [comment]
Discovered a bunch of flakies at https://github.com/filecoin-project/lotus/actions/runs/10041921475/job/27751143865

AND

https://github.com/filecoin-project/lotus/actions/runs/10055228046/job/27791473471

**Comment by rvagg** [comment]
Added `TestTraceFilter` which is a new test. @snissn can you quickly have a look at https://github.com/filecoin-project/lotus/actions/runs/10172996595/job/28136413489#step:10:4128 and see if you can suggest why it might be failing? It's getting 4 traces instead of 3 at https://github.com/filecoin-project/lotus/blob/f6978f01725fc8f8ef72cdf83d15aa57b8e076db/itests/eth_transactions_test.go#L705, which is weird. I'd guess it's a race if it was 2 instead of 3 but one more? What could that be finding?

**Comment by rvagg** [comment]
I've seen more instances of the above failure now.

Plus another failure in the same itest: https://github.com/filecoin-project/lotus/actions/runs/10298551550/job/28504189068?pr=12327

```
        	Error Trace:	/home/runner/work/lotus/lotus/itests/eth_transactions_test.go:701
        	Error:      	Received unexpected error:
        	            	cannot get trace for block 14: failed to get tipset: requested a future epoch (beyond 'latest')
        	Test:       	TestTraceFilter
```

@snissn we're going to need your help on these I think.

**Comment by rvagg** [comment]
manual-onboarding flaky TestManualSectorOnboarding/WithRealProofs: https://github.com/filecoin-project/lotus/actions/runs/10300409613/job/28509755121?pr=12327
looks like a disagreement between the blockminer and the manual miner about when PoST is supposed to be submitted, blockminer pauses mining to wait for message, manual miner doesn't seem to think it needs one; seems like an unaccounted-for edge case?

**Comment by rvagg** [comment]
I seem to have introduced a flaky test in gateway when looking at rate limits: https://github.com/filecoin-project/lotus/actions/runs/10820940825/job/30022021725#step:9:998

```
    gateway_test.go:398: expected end: 2024-09-11 23:04:13.504329557 +0000 UTC m=+20.756356531, now: 2024-09-11 23:04:09.391624721 +0000 UTC m=+16.643651706, allowPad: 800ms, actual delta: -4.112704738s
    gateway_test.go:399: 
        	Error Trace:	/home/runner/work/lotus/lotus/itests/gateway_test.go:399
        	Error:      	Max difference between 2024-09-11 23:04:13.504329557 +0000 UTC m=+20.756356531 and 2024-09-11 23:04:09.39166259 +0000 UTC m=+16.643689571 allowed is 800ms, but difference was 4.11266696s
        	Test:       	TestGatewayRateLimits
```

That's saying that it's completing a series of requests ~4s faster than it should, the max allowed padding is 800ms so it's way faster than even the outer bounds of the timing. The test sets up an environment where it _should_ slow down requests in a fairly predictable way. It's still got lots of real-world effects feeding into it that make it variable, so something's in the way.

**Comment by rvagg** [comment]
`TestContractInvocationMultiple` is flaky, here's the latest: https://github.com/filecoin-project/lotus/actions/runs/11142239872/job/30964794231

Sadly my fault again https://github.com/filecoin-project/lotus/pull/12431, but I was testing something in a way that hasn't been properly tested so it makes me sus about the underlying behaviour.

**Comment by masih** [comment]
`TestEthBlockHashesCorrect_MultiBlockTipset` in `itest-eth_block_hash` seems to be flaky:
* [initial run](https://github.com/filecoin-project/lotus/actions/runs/11389123242/job/31687718841?pr=12608) failed.
* but [re-run](https://github.com/filecoin-project/lotus/actions/runs/11389123242/job/31688349041?pr=12608) passed.
* for [unrelated changes](https://github.com/filecoin-project/lotus/pull/12608).

**Comment by rvagg** [comment]
Reopened https://github.com/filecoin-project/lotus/issues/12566 to own the gateway issue because I'm about to `t.Skip` that one and want it clear that it needs to be fixed.

**Comment by rvagg** [comment]
TestEthBlockHashesCorrect_MultiBlockTipset again:

https://github.com/filecoin-project/lotus/actions/runs/26885392000/job/79296227410?pr=13644

```
      eth_block_hash_test.go:79: 
          	Error Trace:	/home/runner/work/lotus/lotus/itests/eth_block_hash_test.go:79
          	Error:      	Not equal: 
          	            	expected: 0x4a817c800
          	            	actual  : 0x2540be400
          	Test:       	TestEthBlockHashesCorrect_MultiBlockTipset
          	Messages:   	expected gas limit to be 20000000000 for 2 blocks
```

i.e. expected 2 * BlockGasLimit (20B) but got 1 * (10B), the tipset had one block instead of two.

From the itest code "let the chain run a little bit longer to minimise the chance of reorgs" .. i.e. this is known flaky by design.

```
  failed to submit newly mined block: sync to submitted block failed:
  collectChain failed: failed to sync fork: doRequest failed for all peers
```
