### ISSUE TITLE
Deprecate the "releases" branch

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#12374]
## Done Criteria
1. The "releases" branch ceases to work (i.e., not able to checkout the branch and build Lotus Node or Miner by default)
2. Anyone who attempts the above is given clear messaging and pointers to alternatives
3. References to the branch are removed/updated

## Why Important
1. (main reason) Remove ambiguity - `releases` goal was to point to the latest stable tagged release of Lotus software for convenience and script.  This worked when Lotus Node and Miner were released together, but with the [2024Q3 split of releasing Lotus Node and Miner separately](https://github.com/filecoin-project/lotus/issues/12010), there isn't necessarily a single commit to track for the latest released software of both.    
2. (minor reason) Time savings - As Lotus Node maintainers seek to [cleanup and simplify the Lotus Node release process](https://github.com/filecoin-project/lotus/issues/12072), updating the `releases` was an additional manual step.

## User/Customer
Maintainers and users building from source

## Notes
1. This is falling out from working on https://github.com/filecoin-project/lotus/issues/12072 .  It is tracked separately to give it more visibility and enable tighter scoped discussed, because it can be done separately, and to ensure none of the details get lost in a larger issue.
2. The initial "Task Proposal" is an initial proposal by @BigLep .  Feedback and suggestions welcome.  I wanted to get an issue started so we could start linking to it.

```[tasklist]
## Task Proposal
- [x] Update the README and makefile in `releases` branch to make the state of the branch clear and point to more info/alternatives.  https://github.com/filecoin-project/lotus/pull/12375
- [x] Remove references from GitHub workflows/templates: https://github.com/filecoin-project/lotus/pull/12396
- [x] Remove references in lotus-docs: https://github.com/filecoin-project/lotus-docs/pull/755
- [x] Archive or protect the branch so new functionality is accidentally pushed to the branch: https://github.com/filecoin-project/lotus/settings/branch_protection_rules/22005102
```

**Comment by BigLep** [comment]
A draft of changes to the `releases` branch itself: https://github.com/filecoin-project/lotus/pull/12375

**Comment by BigLep** [comment]
> Archive or protect the branch so new functionality is accidentally pushed to the branch
I udpated https://github.com/filecoin-project/lotus/settings/branch_protection_rules/22005102 so `releases` is read-only: 
<img width="743" alt="image" src="https://github.com/user-attachments/assets/c79534f9-175c-43c9-8028-dffedd2f89da">

We just have a couple of docs updates to merge and then we can close this issue.

**Comment by BigLep** [comment]
I'll items addressed.  Resolving.

**Comment by rjan90** [comment]
I have opened up #12399 targeting the `releases` branch here to correct a link that got overwritten accidentally. I have therefore temporarily unlock the releases branch: https://github.com/filecoin-project/lotus/settings/branch_protection_rules/22005102 so that this change can land. I will lock the branch again, once the #12399 PR has been merged.
