### ISSUE TITLE
Meta tracking Issue for the ChainIndexer implementation

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#12456]
For https://github.com/filecoin-project/lotus/issues/12453

This is a meta tracking issue for all the work that needs to happen to land and ship the `ChainIndexer` described in https://github.com/filecoin-project/lotus/issues/12453.

**PRs**
- [ ] Land `ChainIndexer` implementation at https://github.com/filecoin-project/lotus/pull/12421
- [ ] Land Migration/Backfilling/Diagnostics tooling for the `ChainIndexer` at https://github.com/filecoin-project/lotus/pull/12450

### TODO
- [ ] Smoke testing on @rvagg's mainnet node and test re-indexing on that node as it is a snapshot synced node with splitstore enabled.
- [ ] Work with Glif to deploy the `ChainIndexer` on their FEVM archival node and re-index the entire archived chain history in the `ChainIndexer`. OKU should then be able to use that node for their app. A green light from Glif & OKU is what we need here to then ship this out to all users.
- [ ] Write a document explaining the mechanics of re-indexing/backfilling/diagnostics/inspection of the `ChainIndexer` and explain how RPC providers can use the RPCs/CLI commands being built out in  https://github.com/filecoin-project/lotus/pull/12450 for all of those use cases.
- [ ] Document the Config changes introduced in https://github.com/filecoin-project/lotus/pull/12421 so users understand the knobs they can turn on/off for the `ChainIndexer`. 
- [ ] Document clean up process for the existing `MsgIndex`,`EthTxIndex` and `EventIndex` (should be as simple as getting rid of the Sqlite DBs in the Lotus repo).
