### ISSUE TITLE
Create tags with bot account

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#12496]
## Done Criteria
Lotus release automation uses a bot to create the tag 

## Why Important
Not that important, but it causes confusion when a release goes out and @galargh's name is tied to it ([latest example](https://filecoinproject.slack.com/archives/C027TQMUVJN/p1726515409792729)). 

## User/Customer
Mostly this is for maintainers

## Notes
1. This happens because CI uses @galargh token because we have protection rules on tag creation and we can only allow-list actual users, not apps. 
2. The secret we need to update is `TAG_CREATE_GITHUB_TOKEN`
3. We need a bot account with these permissions:
![image](https://github.com/user-attachments/assets/3fbef4e9-858e-4bc4-a03a-a0bbf451ac87)

```[tasklist]
## Tasks
- [x] Create filoz-bot account
- [x] Add filoz-bot account to filecoin-project
- [x] Create personal access token
- [x] Update secret `TAG_CREATE_GITHUB_TOKEN`
```

**Comment by BigLep** [comment]
@rjan90 : I can take this unless you have already started on it.  I would do the tasks listed in the issue description.

Cc @jennijuju since you were asking about this recently.

**Comment by galargh** [comment]
If you have any further questions about this, please let me know :)

**Comment by BigLep** [comment]
@FilOzzy lives: https://github.com/FilOzzy

Added to filecoin-project: https://github.com/filecoin-project/github-mgmt/pull/96

Created PAT matching screenshot above:

https://github.com/settings/personal-access-tokens
<img width="824" alt="Image" src="https://github.com/user-attachments/assets/757588c9-6cd7-4d04-b30b-8f463e512783" />

Updated `TAG_CREATE_GITHUB_TOKEN`:

https://github.com/filecoin-project/lotus/settings/secrets/actions
<img width="800" alt="Image" src="https://github.com/user-attachments/assets/21fb7f8e-25ee-4c93-b969-457a59acb01c" />

**Comment by BigLep** [comment]
I'm marking this as resolved since all known steps are complete.  We'll find out in the next Lotus release whether I messed anything up by looking at [#fil-lotus-announcements](https://filecoinproject.slack.com/archives/C027TQMUVJN) during the next release.

**Comment by BigLep** [comment]
Also, for visibility, the FilOzzy GitHub credentials are in FilOz's Infra 1password vault.
