### ISSUE TITLE
Benchmark nv24 migration

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#12554]
```[tasklist]
## Tasks
- [x] Calibration: run the migration in "offline" and "online" mode and comment on this issue with findings (see "notes" below for template suggestion) https://github.com/filecoin-project/lotus/issues/12554#issuecomment-2399478125
- [x] Mainnet: run the migration in "offline" and "online" mode and comment on this issue with findings (see "notes" below for template suggestion) https://github.com/filecoin-project/lotus/issues/12554#issuecomment-2396121347 and https://github.com/filecoin-project/lotus/issues/12554#issuecomment-2396362019
- [x] Param finalization: based on time and memory usage of the experiments, we need to settle on the correct number of epochs for premigration: https://github.com/filecoin-project/lotus/issues/12554#issuecomment-2396421792
- [x] Expected durations (premigration and migration) and memory requirements are added to Lotus CHANGELOG: https://github.com/filecoin-project/lotus/pull/12564
```

## Notes
* "offline" and "online" mode are describe in https://github.com/filecoin-project/lotus/issues/12432
* Use the same "benchmark template" found in https://github.com/filecoin-project/lotus/issues/12432 for commenting on this issue with results.
* We should do the benchmark on a "lower powered machine" so we get a better sense of the worst case.

**Comment by rjan90** [comment]
### Spec: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz, 128GiB RAM, SSD.

**In offline mode following the [tutorial here](https://lotus.filecoin.io/kb/test-migration/#benchmark-migration-in-offline-mode):**

```
./lotus-shed migrate-state --repo=/mnt/lotuschain/.lotus 24 bafy2bzacebyo2oz2sepnshikeuzncs56ehvyfme5weueebxmnuyo7gvs2tihc
REMINDER: If you are running this, you likely want to ALSO run the continuity testing tool!
2024-10-07T09:11:44.399+0200	INFO	bundle	bundle/bundle.go:60	manifest cid: bafy2bzaceakwje2hyinucrhgtsfo44p54iw4g6otbv5ghov65vajhxgntr53u
----------
completed round actual (without cache), took  1m1.439523705s
----------
completed premigration, took  45.345828372
completed round actual (with cache), took  33.843354743s
```

Max Memory usage was 15GiB

**Comment by rjan90** [comment]
### Spec: CPU: AMD EPYC 7F32 8-Core Processor, RAM: 512GiB, NVMe RAID

**In offline mode following the [tutorial here](https://lotus.filecoin.io/kb/test-migration/#benchmark-migration-in-offline-mode):**

```
./lotus-shed migrate-state --repo=/mnt/nvmeraid0/daemon 24 bafy2bzaced2jgqbrv5bvoh3itk64xrnb4rbdxszbaylxjab2tkt74svkuffgw
2024-10-07T09:10:00.691Z	INFO	bundle	bundle/bundle.go:60	manifest cid: bafy2bzacecbueuzsropvqawsri27owo7isa5gp2qtluhrfsto2qg7wpgxnkba
----
completed round actual (without cache), took  27.183082707s
----
completed premigration, took  35.814424291s
completed round actual (with cache), took  24.831157465s
```

**Comment by rjan90** [comment]
> Param finalization: based on time and memory usage of the experiments, we need to settle on the correct number of and epochs for premigration

Given the current numbers one the split store enabled nodes, we could potentially drop the pre-migration epoch to be 60 epochs before the network upgrade. But given that we have not tested this on an archival node, I feel like the default 120 epochs is fine.

**Comment by rjan90** [comment]
> Expected durations (premigration and migration) and memory requirements are added to Lotus CHANGELOG.

I have added the expected durations and memory requirements to the Changelog in the v1.30.0-rc1 prep here: https://github.com/filecoin-project/lotus/pull/12564

**Comment by BigLep** [comment]
@rjan90 : I pasted in the suggested issue tasks as directed from https://docs.google.com/document/d/1KKJj2COb0vIqAQh-4F7fflJjxiTgGrU9oT9B461nsgg/edit (which I backported to https://docs.google.com/document/d/1-KVWo7O_WwdalherQzvAfU9tWOUizemV_0NNJgAWmPo/edit)

**Comment by rjan90** [comment]
### Calibration migration benchmark with Spec: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz, 128GiB RAM, SSD.

**In offline mode following the [tutorial here](https://lotus.filecoin.io/kb/test-migration/#benchmark-migration-in-offline-mode):**

```
migration height  2035235
old cid  bafy2bzacedk7jubgu3c33nflomgphmto2ajec7edcvrszuedoenzv6woaibe6
new cid  bafy2bzacecza56ewlqcpqcf7oz2nwcveiigxgcbsupuv46qyrza2fp7hejiks
completed round actual (without cache), took  1.25078817s
---
completed premigration, took  1.520957691s
completed round actual (with cache), took  1.07015202s
---
```

**In online mode following the [tutorial here](https://lotus.filecoin.io/kb/test-migration/#benchmark-migration-in-online-mode):**

Pre-Migration in "online-mode":

```
```

And the actual migration in "online-mode":

```
```

**Comment by rjan90** [comment]
Closing this ticket as [all the tasks](https://github.com/filecoin-project/lotus/issues/12554#issue-2565809090) has been completed.
