### ISSUE TITLE
Verified Client Support

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#2130]
This issue tracks support work across Lotus & Markets to support verified clients and verified deals

## Tasks

- [x] spec-actors support for verified deals in `market.DealProposal`
- [x] update markets to take verified deal attribute for `ProposeStorageDeal`
- [x] write a StateAPI method in Lotus for `StateGetClientDataCap(tsKey, address.address) (verifreg.DataCap, error)` (error != nil if client is not verified)
- [x] update `lotus client deal` to take an optional verified deal parameter. Default value is 'yes' if verified, 'no' if not verified
- [x] update markets to check on the Provider side when they receive a proposal for a verified deal that the DataCap for the client is more than the size of the deal, and reject if not, before data transfer. Requires new node method: 
`GetDataCap(tok tipset.Token, address.Address) (verifreg.DataCap, error)`
- [x] update market adapter to implement GetDataCap (just call state API method)
