### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#3871]
# Lotus 0.9.0 Release

This is a large consensus-breaking release that will be introduced to the ignition. The goal is to test out a major specs-actor upgrade: this includes the ability to switch between 2 actors versions as needed, the operations efforts required for such upgrades, and the mining community's ability to consume such an upgrade release.

## Estimated shipping date

Wednesday, October 7, 2020.

### Must haves

- [x] Land #3936, start using actors v2
- [x] Land #3589
- [x] Land #4188:  Use MinerPoStLookbackEligibleForElection and MinerEligibleForElection to determine eligibility (see #3378)
- [ ] **Run a full chain import** (in progress)
- [x] Land #4186: Make default address encoding to `f`
- [x] Land #4160: Modify StateCircSupply to account for faucet (research-priv 349)
- [x] Land #4199: Update specs-actors [one last time](https://www.youtube.com/watch?v=Wg92RrNhB8s) to the tagged version (https://github.com/filecoin-project/specs-actors/pull/1215 needs to land)
- [x] Confirm 130800, and set that in code (Friday the 9th, 0800 UTC)

### Should haves

- [x] Land #4189: Expose CLI to change owner address of a miner actor: #3951 
- [x] Land #4190: Set WinningPoStSectorLookback to finality
- [x] Land #3697: Error when actor panics directly
- [x] Include [this](https://github.com/filecoin-project/go-amt-ipld/pull/35#pullrequestreview-503238444).

### Not gonna have

- [ ] Abort if beneficiary is not found: #3479
- [ ] Guard against self beneficiary when deleting actor #3478
- [ ] 387 research
- [ ] Lotus fetches drand from chain backwards with null blocks while specs fetches forward: #3613
- [ ] 364 research (more important than 3613)
- [ ] Restrict actor exit codes to non-system codes: #3656 (Approved already)
- [ ] Actor method params deserialization error exit code: #3730
- [ ] (if not covered by above PRs), resolve #3015 and #3548 
- [ ] Audit any param changes in the upgrade, especially stuff we might have hard-copied into Lotus like [this](https://github.com/filecoin-project/lotus/blob/beba92aed42f70ef7cf4315cc1b728e2c8d41c67/build/params_shared_vals.go#L106).

**Comment by zhangshuiyong** [comment]
Hop fix selfish-packing bug. This is a big bug

**Comment by alanshaw** [comment]
Any chance to get some other concensus-breaking changes in? I have the following PRs open that seem fairly innocuous:

* https://github.com/filecoin-project/lotus/pull/3478
* https://github.com/filecoin-project/lotus/pull/3479
* https://github.com/filecoin-project/lotus/pull/3656 (Approved already)
* https://github.com/filecoin-project/lotus/pull/3730

This one also but it's more controversial and needs input:

* https://github.com/filecoin-project/lotus/pull/3697

**Comment by alanshaw** [comment]
My comment above can be ignored - this is not a free for all concensus breaking release so those PRs (as they stand cannot go in), this is concensus breaking that is _upgradable_ within the network.

**Comment by arajasek** [comment]
We also want https://github.com/filecoin-proect/lotus/issues/3935

**Comment by nicola** [comment]
What is the new estimate shipping date for this?

**Comment by arajasek** [comment]
@nicola Updated the issue, new shipping date is October 7.
