### ISSUE TITLE
Single verified deal with insufficient cap makes all published deals fail

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#5661]
### Edited 2021-08-16

blocked by https://github.com/filecoin-project/specs-actors/issues/1375 for fixing from the root.

However, in lotus do a check to see if the client datacap is sufficient, if insufficient: 
- [ ] reject the deal upon receiving the deal
- [ ] exclude the deal before sending out `PubishStorageDeals`
- [ ] exclude the deal before sealing it to a sector and before sending out the `PreCommitSector` and `PreCommitSectorBatch` message

___

Below error is triggered by this[ line](https://github.com/filecoin-project/specs-actors/blob/845089a6d2580e46055c24415a6c32ee688e5186/actors/builtin/market/market_actor.go#L271) in spec-actor and is caused by insufficient datacap from client side. This is causing the all deals that were packed in one `PublishStorageDeals` messages to be fialed for provider.

Also on client side, there is no warning showing they are lack of datacap.

Ideally, imo the client datacap shout be locked at one stage and lotus should do client datacap validatioon for the deals before batch them into a message.

**Log** 
```2021-02-22T22:58:34.211Z        INFO    markets loggers/loggers.go:20   storage provider event  {"name": "ProviderEventFailed", "proposal CID": "bafyreic6byfamm3l4oanhpptx3hyycbgr24jfikbc6by7iezwpowt564uq", "state": "StorageDealError", "message": "error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 17, reason: failed to add verified deal for client: (RetCode=17)"}```

**Comment by raulk** [comment]
I think there are two problems here:

1. The fact that a client is not warned when attempting to make a deal with insufficient datacap (UX).
2. The fact that a single failed verified deal can make the entire batch fail. Is this atomicity intentional? Can't we only activate the deals that succeeded?

**Comment by jennijuju** [comment]
> I think there are two problems here:
> 
> 1. The fact that a client is not warned when attempting to make a deal with insufficient datacap (UX).
> 2. The fact that a single failed verified deal can make the entire batch fail. Is this atomicity intentional? Can't we only activate the deals that succeeded?

for 2 -> https://github.com/filecoin-project/specs-actors/issues/1375

**Comment by raulk** [comment]
@jennijuju I took the liberty of renaming the issue to be more specific. Please roll back if it was a mistake.

**Comment by PatrickDeuse** [comment]
possible steps to be taken:

- check if the data cap is still available before accepting the deal miner side (will work until the top-up data caps FIP is implemented)
- check / proposal if the data cap is still available before batching
- check if the proposals already batched will use the available data cap before adding another one

since non of this happens on chain the result is not a fix for the problem but a "work around" to lower the possible impact of malicious behavior on the clients side

**Comment by neondragon** [comment]
Could we expand the scope of this issue -- this happens for _any_ reason that the lotus node rejects the PublishStorageDeal message, not just insufficient DataCap.

I had a batch of 6 deals move to StorageDealError yesterday due to 5 being rejected by the node with: `error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock client funds: insufficient balance for addr f0397376: escrow balance 8876681162585711668 < locked 8867992391647711668 + required 11500000000000000 (RetCode=19)`

This

- Has abuse potential
- Encourages miners to reject deals while they are working with other deals that they do not want to risk

I think that Lotus should:

1. Validate deals before publishing. If lotus-miner could first check validity of each deal with the node before sending a PublishStorageDeals message, it could leave invalid deals in the pending queue and publish only the valid ones.
2. Not discard deals with transient errors. The client could fix their datacap problem, or their market balance problem, and then the deal can be published. An online 32GiB transfer can take a client a long time and discarding it means having to tell the client to make a new deal and send their data all over again, instead of just telling a client to add market balance.
3. Give miners a way to abort deals. We may know that a client will never fix their issue, or that the StartEpoch is too soon and we don't want to continue accepting the deal after a long enough delay. So Lotus needs to not abort deals if it can possibly avoid it, and the miner needs a command to make the decision to abort a deal at their discretion to free up the publish queue.

**Comment by jimpick** [comment]
Is this the same issue as https://github.com/filecoin-project/lotus/issues/6614 ?

I was helping somebody debug an error on Slack which seems to be the same https://filecoinproject.slack.com/archives/C01AZP8BKRQ/p1626488189201500

**Comment by magik6k** [comment]
Fixed by https://github.com/filecoin-project/lotus/pull/7234
