### ISSUE TITLE
Restart resilience for retrievals

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/lotus#5914]
This issue is an Epic to keep track of tasks that must be completed in order for a retrieval deal to resume after the network goes down or the client / provider is restarted.

Currently go-fil-markets does not recover from a network failure, or a peer going down during a retrieval.

Tasks:
- [ ] Create integration test that bounces the network connection during data transfer in a retrieval deal https://github.com/filecoin-project/go-fil-markets/issues/533 https://github.com/filecoin-project/go-data-transfer/pull/193
- [ ] Create integration test that bounces the network connection during all significant retrieval deal states https://github.com/filecoin-project/go-fil-markets/issues/534
- [ ] Understand and implement go-fil-markets changes
  - Request validator needs to support reading state from an existing deal (instead of always creating a new one)
  - Voucher accounting must sync on client and provider https://github.com/filecoin-project/go-data-transfer/issues/151 https://github.com/filecoin-project/go-data-transfer/issues/184 https://github.com/filecoin-project/go-data-transfer/pull/193
- [ ] Implement changes to go-data-transfer
  - [ ] Channel monitor should restart retrieval deal when connection goes down https://github.com/filecoin-project/go-data-transfer/pull/190
  - [ ] Fix voucher / data sent accounting for retrieval deals https://github.com/filecoin-project/go-data-transfer/pull/193
- [x] Create integration tests in go-fil-markets for retrieval with unseal price > 0 https://github.com/filecoin-project/go-fil-markets/issues/527
- [ ] Create testground tests for deal data transfer restarts https://github.com/filecoin-project/lotus/issues/5740

**Comment by dirkmc** [comment]
Fixed by https://github.com/filecoin-project/lotus/pull/6149
