### ISSUE TITLE
lotus v1.9.0

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#5977]
# Lotus v1.9.0 Release

## 🗺 What's left for the release

> Note: This section is still WIP and should be finalized on Apr 9th.

 - [x] Integrate proof v6.1.0 [#5816](https://github.com/filecoin-project/lotus/issues/5816)
 - [x] Integrate proof v7.0.0 and new ffi [#6129](https://github.com/filecoin-project/lotus/issues/6129)
 - [x] Update to go-fil-markets-v1.2.5 [#5941](https://github.com/filecoin-project/lotus/pull/5941) 
 - [x] Binaries for RCs (see https://github.com/filecoin-project/lotus/issues/6030)
 - [ ] ~Lotus Lite: Check backing node version on startup #6146~
 - [ ] ~api doc~

## 🚢 Estimated shipping date

- [x] 2021-04-13 ~v1.7.0-rc1~ 1.9.0-rc1
- [x] 2021-05-03 1.9.0-rc2
- [x] 2021-05-06 1.9.0-rc3
- [x] 2021-05-14 1.9.0-rc5
- [x] ~2021-04-27~ ~2021-05-10~ 2021-05-17 [v1.9.0](https://github.com/filecoin-project/lotus/tree/v1.9.0)

## Changelog

This is an optional Lotus release that introduces various improvements to the sealing, mining, and deal-making processes.

## Highlights

- OpenRPC Support (https://github.com/filecoin-project/lotus/pull/5843)
- Take latency into account when making interactive deals (https://github.com/filecoin-project/lotus/pull/5876)
- Update go-commp-utils for >10x faster client commp calculation (https://github.com/filecoin-project/lotus/pull/5892)
- add `lotus client cancel-retrieval` cmd to lotus CLI (https://github.com/filecoin-project/lotus/pull/5871)
- add `inspect-deal` command to `lotus client` (https://github.com/filecoin-project/lotus/pull/5833)
- Local retrieval support (https://github.com/filecoin-project/lotus/pull/5917)
- go-fil-markets v1.1.9 -> v1.2.5
  - For a detailed changelog see https://github.com/filecoin-project/go-fil-markets/blob/master/CHANGELOG.md
- rust-fil-proofs v5.4.1 -> v6.1.0
  - For a detailed changelog see https://github.com/filecoin-project/rust-fil-proofs/blob/master/CHANGELOG.md

## Changes
- storagefsm: Apply global events even in broken states (https://github.com/filecoin-project/lotus/pull/5962)
- Default the AlwaysKeepUnsealedCopy flag to true (https://github.com/filecoin-project/lotus/pull/5743)
- splitstore: compact hotstore prior to garbage collection (https://github.com/filecoin-project/lotus/pull/5778)
- ipfs-force bootstrapper update (https://github.com/filecoin-project/lotus/pull/5799)
- better logging when unsealing fails (https://github.com/filecoin-project/lotus/pull/5851)
- perf: add cache for gas permium estimation (https://github.com/filecoin-project/lotus/pull/5709)
- backupds: Compact log on restart (https://github.com/filecoin-project/lotus/pull/5875)
- backupds: Improve truncated log handling (https://github.com/filecoin-project/lotus/pull/5891)
- State CLI improvements (State CLI improvements)
- API proxy struct codegen (https://github.com/filecoin-project/lotus/pull/5854)
- move DI stuff for paychmgr into modules (https://github.com/filecoin-project/lotus/pull/5791)
- Implement Event observer and Settings for 3rd party dep injection (https://github.com/filecoin-project/lotus/pull/5693)
- Export developer and network commands for consumption by derivatives of Lotus (https://github.com/filecoin-project/lotus/pull/5864)
- mock sealer: Simulate randomness sideeffects (https://github.com/filecoin-project/lotus/pull/5805)
- localstorage: Demote reservation stat error to debug (https://github.com/filecoin-project/lotus/pull/5976)
- shed command to unpack miner info dumps (https://github.com/filecoin-project/lotus/pull/5800)
- Add two utils to Lotus-shed (https://github.com/filecoin-project/lotus/pull/5867)
- add shed election estimate command  (https://github.com/filecoin-project/lotus/pull/5092)
- Add --actor flag in lotus-shed sectors terminate (https://github.com/filecoin-project/lotus/pull/5819)
- Move lotus mpool clear to lotus-shed (https://github.com/filecoin-project/lotus/pull/5900)
- Centralize everything on ipfs/go-log/v2 (https://github.com/filecoin-project/lotus/pull/5974)
- expose NextID from nice market actor interface (https://github.com/filecoin-project/lotus/pull/5850)
- add available options for perm on error (https://github.com/filecoin-project/lotus/pull/5814)
- API docs clarification: Document StateSearchMsg replaced message behavior (https://github.com/filecoin-project/lotus/pull/5838)
- api: Document StateReplay replaced message behavior (https://github.com/filecoin-project/lotus/pull/5840)
- add godocs to miner objects (https://github.com/filecoin-project/lotus/pull/2184)
- Add description to the client deal CLI command (https://github.com/filecoin-project/lotus/pull/5999)
- lint: don't skip builtin (https://github.com/filecoin-project/lotus/pull/5881)
- use deal duration from actors (https://github.com/filecoin-project/lotus/pull/5270)
- remote calc winningpost proof (https://github.com/filecoin-project/lotus/pull/5884)
- packer: other network images (https://github.com/filecoin-project/lotus/pull/5930)
- Convert the chainstore lock to RW (https://github.com/filecoin-project/lotus/pull/5971)
- Remove CachedBlockstore (https://github.com/filecoin-project/lotus/pull/5972)
- remove messagepool CapGasFee duplicate code (https://github.com/filecoin-project/lotus/pull/5992)

## Fixes
- return buffers after canceling badger operation (https://github.com/filecoin-project/lotus/pull/5796)
- avoid holding a lock while calling the View callback (https://github.com/filecoin-project/lotus/pull/5792)
- storagefsm: Trigger input processing when below limits (https://github.com/filecoin-project/lotus/pull/5801)
- After importing a previously deleted key, be able to delete it again (https://github.com/filecoin-project/lotus/pull/4653)
- fix StateManager.Replay on reward actor (https://github.com/filecoin-project/lotus/pull/5804)
- make sure atomic 64bit fields are 64bit aligned (https://github.com/filecoin-project/lotus/pull/5794)
- Import secp sigs in paych tests (https://github.com/filecoin-project/lotus/pull/5879)
- fix ci build-macos (https://github.com/filecoin-project/lotus/pull/5934)
- Fix creation of remainder account when it's not a multisig (https://github.com/filecoin-project/lotus/pull/5807)
- Fix fallback chainstore (https://github.com/filecoin-project/lotus/pull/6003)
- fix 4857: show help for set-addrs (https://github.com/filecoin-project/lotus/pull/5943)
- fix health report (https://github.com/filecoin-project/lotus/pull/6011)

## ✅ Release Checklist

First steps:

  - [x] Fork a new branch (`release/vX.Y.Z`) from `master` and make any further release related changes to this branch. If any "non-trivial" changes get added to the release, uncheck all the checkboxes and return to this stage.
  - [ ] Prep the changelog using `bin/mkreleaselog`, and add it to `CHANGELOG.md`
  - [x] Bump the version in `version.go` in the `master` branch to `vX.(Y+1).0-dev` - https://github.com/filecoin-project/lotus/pull/6028
    
Prepping an RC:

- [x] version string in `build/version.go` has been updated (in the `release/vX.Y.Z` branch).
- [x] tag commit with `vX.Y.Z-rcN`
- [x] cut a pre-release [here](https://github.com/filecoin-project/lotus/releases/new?prerelease=true)

Testing an RC:

- [x] **Stage 0 - Automated Testing**
  - Automated Testing
    - [x] CI: Ensure that all tests are passing. * - there is one test that is flaky)
    - [x] Testground tests

- [ ] **Stage 1 - Internal Testing**
  - Upgrade our testnet infra
    - [x] 1 bootstrap node
    - [x] 1 miner
    - [x] Scratch nodes
    - [x] Wait 24 hours, confirm nodes stay in sync
    - [x] Remaining testnet infra
  -  Upgrade our mainnet infra
    - [x] Subset of development full archival nodes
    - [x] Subset of bootstrappers (1 per region)
    - [x] Confirm nodes stay in sync
    - Metrics report
        - Block validation time
        - Memory / CPU usage
        - Number of goroutines
        - IPLD block read latency
        - Bandwidth usage
    - [x] If anything has worsened significantly, investigate + fix
  - Confirm the following work (some combination of Testground / Calibnet / Mainnet / beta users)
    - [x] Seal a sector
    - [ ] make a deal
    - [ ] Submit a PoSt
    - [ ] (optional) let a sector go faulty, and see it be recovered
    
- [x] **Stage 2 - Community Dev Testing**
  - [x] Inform beta miners (@lotus-early-testers-miner in Filecoin Slack #fil-lotus)
  - [ ] Ask close ecosystem partners to test their projects (@lotus-early-testers-eco-dev in Filecoin slack #fil-lotus)
    - [x] Powergate
    - [x] Glif
    - [x] Zondax
    - [ ] Stats dashboard
    - [ ] Community dashboards
    - [x] Infura
    - [ ] Sentinel
    - [x] Protofire
    - [ ] Fleek

- [ ] **Stage 3 - Community Prod Testing**
  - [x] Documentation
    - [x] Ensure that [CHANGELOG.md](https://github.com/filecoin-project/lotus/blob/master/CHANGELOG.md) is up to date
    - [ ] Check if any [config](https://docs.filecoin.io/get-started/lotus/configuration-and-advanced-usage/#configuration) updates are needed
  - [ ] Invite the wider community through (link to the release issue):
    - [ ] Create a lotus disucssion, example [here](https://github.com/filecoin-project/lotus/discussions/5595)
    - [ ] Link the disucssion in #fil-lotus on Filecoin slack
    
- [ ] **Stage 4 - Release**
  - [ ] Final preparation
    - [x] Verify that version string in [`version.go`](https://github.com/ipfs/go-ipfs/tree/master/version.go) has been updated.
    - [x] Ensure that [CHANGELOG.md](https://github.com/filecoin-project/lotus/blob/master/CHANGELOG.md) is up to date
    - [x] Ensure that [README.md](https://github.com/filecoin-project/lotus/blob/master/README.md) is up to date
    - [x] Merge `release-vX.Y.Z` into the `releases` branch.
    - [x] Tag this merge commit (on the `releases` branch) with `vX.Y.Z`.
    - [x] Cut the release [here](https://github.com/filecoin-project/lotus/releases/new?prerelease=true&target=releases).
    - [x] Final announcements
        - [x] Update network.filecoin.io
        - [x] Add a comment when the final release is tagged, example [here](https://github.com/filecoin-project/lotus/discussions/5905#discussioncomment-571752)
        - [x] repost in #fil-lotus in filecoin slack

- [x] **Post-Release**
  - [x] Merge the `releases` branch back into `master`, ignoring the changes to `version.go` (keep the `-dev` version from master).
  - [x] Update [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) with any improvements determined from this latest release iteration.
  - [x] Create an issue using [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) for the _next_ release.
## ❤️ Contributors

< list generated by bin/mkreleaselog >

Would you like to contribute to Lotus and don't know how? Well, there are a few places you can get started:

- TODO

**Comment by jennijuju** [comment]
@dirkmc IIUC, the new market release is not 100% backward compatible and we may want to avoid that if possible. Do we have plans to fix that? If so, can it be done by next Monday?

**Comment by f8-ptrk** [comment]
4 - ensure the docs are in sync

**Comment by vanvank** [comment]
can we upgrade using the latest master which is 1.7.0  for April 12th

**Comment by ProgramAPE** [comment]
The version of rust-fil-proofs will be changed to 1.6.0?  Why not the 6.1.0+ series?

**Comment by BigLep** [comment]
Note that while this was previously listed as Lotus v1.7.0, we have redacted this to v$next until #5948 get addressed, which covers Lotus version naming and how it relates to Network versions.

**Comment by jennijuju** [comment]
modularized lotus-miner wouldnt get in this release

**Comment by jennijuju** [comment]
The team has decided on the version convention philosophy and will update in the discussion and have it in lotus readme soon. but as the result of that conversation, this release will be a feature release that has version v1.7.0

**Comment by jennijuju** [comment]
proof v7.0.0 appears to have issue with gpu as well and this is currently blocked by it

**Comment by jennijuju** [comment]
> proof v7.0.0 appears to have issue with gpu as well and this is currently blocked by it

this is done now

**Comment by BigLep** [comment]
@jennijuju : FYI I added checklist steps for going back and updating the release template based on lessons learned.  This is in the template as well in https://github.com/filecoin-project/lotus/pull/6236
