### ISSUE TITLE
[Meta Issue] Replace Badger in Deal Making with CARv2 and the Sharded DAG Store and test with MRA 

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#6673]
This is a meta-issue to track the work of replacing  Badger from Filecoin deal making with [CARv2](https://github.com/ipld/ipld/blob/master/specs/transport/car/carv2/index.md) and the [Sharded DAG Store](https://github.com/filecoin-project/dagstore/pull/20) and do some solid testing along with the [MRA ](https://github.com/filecoin-project/lotus/pull/6356)changes to ensure a smooth landing.

---
### Pending CARv2 features
- [x] [CARv2 read-write blockstore should support resumption](https://github.com/ipld/go-car/issues/98).
---
### Sharded DAG Store
- [x] TODO.
---
### Markets
- [x] https://github.com/filecoin-project/go-fil-markets/pull/558.
- [x] https://github.com/filecoin-project/go-fil-markets/pull/560.
- [x] Integrate Sharded DAG Store into the Storage Market.
- [x] Integrate Sharded DAG Store into the Retrieval Market.
---
### Lotus
- [x] https://github.com/filecoin-project/lotus/pull/6671 (PR is against the MRA changes).
- [x] Integrate the Sharded DAG Store in the Lotus PR above.       
--- 
### Migration 
- [ ] ~Migration of existing storage client data imports in Badger to CARv2 files:~
-  ~Iterate over all the imported payloads in the storage client's Badger store and migrate them to CARv2 files so clients don't have to re-import them. **_Maybe_** don't clean up the Badger store right away so client can downgrade without losing imports.~

- [ ] Register Shards for all active storage deals on the Miner with the Sharded DAG Store. https://github.com/filecoin-project/go-fil-markets/pull/570
- Iterate over all active storage deals on a Miner and register shards for all of them with the Sharded DAG Store so we can serve retrievals for deals made before the upgrade.
- Raise PR against https://github.com/filecoin-project/lotus/pull/6671.

---
~### Testground testing **_(MRA + CARv2 changes)_**~
- Upgraded client -> upgraded miner (Online storage deal and retrieval).
- Upgraded client -> upgraded miner (Offline storage deal and retrieval).
- Upgraded client-> old miner (Online storage deal and retrieval).
- Upgraded client-> old miner (Offline storage deal and retrieval).
- Old client -> upgraded miner  (Online storage deal and retrieval).
- Old client -> upgraded miner (Offline storage deal and retrieval).
---
### Manual testing on Mainnet **_(MRA + CARv2 changes)_**
- [x] Upgraded client -> upgraded miner (Online storage deal and retrieval).
- [x] Upgraded client -> upgraded miner (Offline storage deal and retrieval).
- [x] Upgraded client-> old miner (Online storage deal and retrieval).
- [x] Upgraded client-> old miner (Offline storage deal and retrieval).
- [x] Old client -> upgraded miner  (Online storage deal and retrieval).
- [x] Old client -> upgraded miner (Offline storage deal and retrieval).
- [x] Old client makes an online storage deal with an old miner -> client upgrades and does a retrieval.
- [x] Old client makes an online storage deal with an old miner -> miner upgrades and then the old client does a retrieval.
---
### Benchmarking **_(MRA + CARv2 changes)_**
- Benchmark storage deal data transfers of the upgrade vs the use of Badger using our Testground tests. 
- Benchmark retrieval deal data transfers of the upgrade vs the use of Badger using our Testground tests.
=> tracking in https://github.com/filecoin-project/lotus/issues/7106.
---
### Testing in the Wild Wild West **_(MRA + CARv2 changes)_**
- [x] Get MinerX fellows to upgrade to the latest changes **_(will likely need to work with product for this)_**. 
- [x] Ask Dealbot and Estuary (nicely) to upgrade and stress-test storage and retrieval deals against Minxer fellows

**Comment by aarshkshah1992** [comment]
cc @jacobheun @raulk for tracking.

**Comment by raulk** [comment]
Merged in #6873.
