### ISSUE TITLE
Finish integrating Sharded DAG Store and CARv2 blockstore resumption in Lotus and Markets

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#6735]
We need to wind down the following work to finish integrating the Sharded DAG Store in Lotus and Markets:

@dirkmc 
- [x] Shard Migration for pre-existing deals.
  - The Sharded DAG Store work for this is being done by @raulk [here](https://github.com/filecoin-project/dagstore/pull/53).
  - Migration in go-fil-markets: https://github.com/filecoin-project/go-fil-markets/pull/570
- [x] Integrate and test the the C[ARv2 blockstore resumption](https://github.com/ipld/go-car/pull/147) functionality.
~~Call [Shard destruction](https://github.com/filecoin-project/dagstore/issues/31) on storage deal expiry/slashing.~~

@aarshkshah1992 
- [x] Use the [Shard recovery](https://github.com/filecoin-project/dagstore/issues/33) API in Markets.
- [x] [Roll back storage client changes ](https://github.com/filecoin-project/lotus/pull/6671#pullrequestreview-703624487)in Lotus and Markets and continue using a Badger store there.
- [x] Document a roll back strategy for this work if we discover bugs that forces us to rollback the Miner release for this one.

**Comment by aarshkshah1992** [comment]
cc @jacobheun for EM magic.

**Comment by aarshkshah1992** [comment]
As discussed with @raulk , we'll probably punt the Shard destruction work to a later date.

**Comment by raulk** [comment]
Merged in https://github.com/filecoin-project/lotus/pull/6671 🎉
