### ISSUE TITLE
Deal Making Tests for M1 (MRA + DAGStore integration)

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#6789]
### Testground tests

_No longer necessary._

- Upgraded client -> upgraded miner (Online storage deal and retrieval).
- Upgraded client-> old miner (Online storage deal and retrieval).
- Old client -> upgraded miner  (Online storage deal and retrieval).
- Old client makes an online storage deal with an old miner -> client upgrades and does a retrieval.
- Old client makes an online storage deal with an old miner -> miner upgrades and then the old client does a retrieval.
- Old client makes an online storage deal with an old miner -> both upgrade and then we do a retrieval.

---
### Manual testing on Sofia Miner 
- Assume Sofia Miner is running a separate Markets process (Take help from @nonsense for this).
- The client we run has data-cap. Please make verified storage deals. 
- Turn on the "offer free retrieval for verified deals" flag in the config so we exercise the Bedrock flow.
- We can do a smoke test for the partial payments flow in the end.

#### End-End testing
- [x] Upgraded Client <-> Upgraded Miner (Online storage deal & retrieval).
- [x] Upgraded Client <-> Upgraded Miner (Offline storage deal & retrieval).

#### Backward compatibility testing
- [x] Upgraded client-> Old Miner (Online storage deal & retrieval).

      Miner
      $ lotus version 
      Daemon:  1.11.0-rc2+mainnet+git.0519cd371+api1.3.0
      Local: lotus version 1.11.0-rc2+mainnet+git.0519cd371

      Client
     $ lotus version
      Daemon:  1.11.1-dev+mainnet+git.d7827da5b+api1.3.0
      Local: lotus version 1.11.1-dev+mainnet+git.d7827da5b

   - **data-cid:** `bafykbzacedsope4lbmvqaxrz2m2yz5wmfs5av6klmavbeygxrlechkhqhqwka`
   - **proposal-cid:** `bafyreieln6cn73c4cpnk5ol5e2s6wjoxplrjyjuybxggayojhocowpy5ha`
   
   ```
   > Recv: 584.6 MiB, Paid 0 FIL, ClientEventBlockstoreFinalized (DealStatusCompleted)
      Success
      $ lotus client retrieve --miner f0127896 
      bafykbzacedsope4lbmvqaxrz2m2yz5wmfs5av6klmavbeygxrlechkhqhqwka /dev/null
   ```
---

- [x] Upgraded client-> Old Miner (Offline storage deal & retrieval).

   ```
    Miner 
    root at sofiaminer in ~/lotus-miner-path 
    $ lotus version
    Daemon:  1.11.0-rc2+mainnet+git.0519cd371+api1.3.0
    Local: lotus version 1.11.0-rc2+mainnet+git.0519cd371
    
    Client
     $ lotus version
     Daemon:  1.11.1-dev+mainnet+git.d7827da5b+api1.3.0
     Local: lotus version 1.11.1-dev+mainnet+git.d7827da5b
     ```
     
   - **data-cid:** `bafykbzacebhevf4dq5llibfn3ncy2flx4jyohqrbgbwbptuymprk7oh3er2xg`
   
   ```
   $ lotus client commP /tmp/613-mb-car
   CID:  baga6ea4seaqc4tsfuwipw3k6nd42lvdpgcnbmfe4i3phekuv6zqqoo2hozohqiy
   Piece size:  1016 MiB
   ```
   
   -  **proposal-cid**: `bafyreicir32axzmexcl7yc4fluxeqpwc63xgaztmmnkd32gtefild5npnu`

  ```
  > Recv: 584.6 MiB, Paid 0 FIL, ClientEventBlockstoreFinalized (DealStatusCompleted)
  Success
  $ lotus client retrieve --miner f0127896 
   bafykbzacebhevf4dq5llibfn3ncy2flx4jyohqrbgbwbptuymprk7oh3er2xg /dev/null
  ```

--- 
- [x] Old client-> Upgraded Miner (Online storage deal & retrieval).

- [x] Old client-> Upgraded Miner (Offline storage deal & retrieval).

#### Shard Migration testing
- [x] Old client makes an online storage deal with an old miner -> client upgrades and does a retrieval.

   ```
   **Miner**
   root at sofiaminer in ~/lotus-miner-path 
   $ lotus version
   Daemon:  1.11.0-rc2+mainnet+git.0519cd371+api1.3.0
   Local: lotus version 1.11.0-rc2+mainnet+git.0519cd371
   
   **Client**
   $ lotus version
   Daemon:  1.11.0-rc2+mainnet+git.0519cd371+api1.3.0
   Local: lotus version 1.11.0-rc2+mainnet+git.0519cd371
   ```
   
   **- data-cid**: `bafykbzaced4drsd2st6dr64oilsumvfq4s7d55jflln4whqd6pebgc5o66q6i`
   
   **- proposal-cid:** `bafyreihtnpqlxj633td5vpv72rg472g7znplp5hk53hmd2eaepi4o5clle`
   
   ```
   Upgraded Client  
   $ lotus version
   Daemon:  1.11.1-dev+mainnet+git.d7827da5b+api1.3.0
   Local: lotus version 1.11.1-dev+mainnet+git.d7827da5b
    
   Miner
   root at sofiaminer in ~/lotus-miner-path 
   $ lotus version
   Daemon:  1.11.0-rc2+mainnet+git.0519cd371+api1.3.0
   Local: lotus version 1.11.0-rc2+mainnet+git.0519cd371
   ```
   
   ```
   > Recv: 584.6 MiB, Paid 0 FIL, ClientEventBlockstoreFinalized (DealStatusCompleted)
   Success
   $ lotus client retrieve --miner f0127896 
   bafykbzaced4drsd2st6dr64oilsumvfq4s7d55jflln4whqd6pebgc5o66q6i /dev/null
   ```

---
- [x] Old client makes an online storage deal with an old miner -> miner upgrades and then the old client does a retrieval.

   ```
   lotus version
   Daemon:  1.11.0-rc2+mainnet+git.0519cd371+api1.3.0
   Local: lotus version 1.11.0-rc2+mainnet+git.0519cd371

   root at sofiaminer in ~/lotus (feat/replace-multistore-carv2) 
   $ lotus version
   Daemon:  1.11.0-rc2+mainnet+git.0519cd371+api1.3.0 
  Local: lotus version 1.11.0-rc2+mainnet+git.0519cd371
   ```

    ```
    lotus client import /tmp/613-mb-file
    Import 6, Root bafykbzacebi4uhadzfdrxo3w6qzebznw74l7w2muvez4hxdtc2ongxco4ygpy
    [ec2-user@ip-172-31-20-161 lotus]$ 
    Proposal (f0127896) CID: bafyreiahmcdp6nc5mifkxzvxoer2pc3yarxnjer4pvorpzcpv3fl2s7l2i 
     ```
     
     ```
     Upgraded Miner
     $ lotus version
     Daemon:  1.11.1-dev+mainnet+git.62044c34b+api1.3.0
     Local: lotus version 1.11.1-dev+mainnet+git.62044c34b
     ```
     
     ```
     > Recv: 584.6 MiB, Paid 0 FIL, ClientEventAllBlocksReceived (DealStatusCompleted)
     Success
    [ec2-user@ip-172-31-20-161 lotus]$ lotus client retrieve --miner f0127896 
     bafykbzacebi4uhadzfdrxo3w6qzebznw74l7w2muvez4hxdtc2ongxco4ygpy /dev/null
     ```
---
- [x] Old client makes an online storage deal with an old miner -> both upgrade and then we do a retrieval.

   ```
   Miner
   $ lotus version
   Daemon:  1.11.1-dev+mainnet+git.62044c34b+api1.3.0
   Local: lotus version 1.11.1-dev+mainnet+git.62044c34b
   
   Client
   lotus]$ lotus version
   Daemon:  1.11.1-dev+mainnet+git.62044c34b+api1.3.0
   Local: lotus version 1.11.1-dev+mainnet+git.62044c34b
   ```
   
   ```
   > Recv: 584.6 MiB, Paid 0 FIL, ClientEventBlockstoreFinalized (DealStatusCompleted)
   Success
   [ec2-user@ip-172-31-20-161 lotus]$ lotus client retrieve --miner f0127896  
   bafykbzacebi4uhadzfdrxo3w6qzebznw74l7w2muvez4hxdtc2ongxco4ygpy /dev/null
   ```

---
- [x] Old client does an offline storage deal with an old miner -> miner upgrades and then we do a retrieval.
     
      ```
      Miner
      $ lotus version                                                                 
      Daemon:  1.11.0-rc2+mainnet+git.0519cd371+api1.3.0                              
      Local: lotus version 1.11.0-rc2+mainnet+git.0519cd371 
      
      Client
      $ lotus version
      Daemon:  1.11.0-rc2+mainnet+git.0519cd371+api1.3.0
      Local: lotus version 1.11.0-rc2+mainnet+git.0519cd371
      ```
             
       ```
      $ lotus client commP /tmp/613-mb-car
      CID:  baga6ea4seaqmycidoxg7ht3qhjjfhkgj7nkol5wysznsdrqcwvol3dbmrseaejy
      Piece size:  1016 MiB
       ```
      
      - **data-cid**=bafykbzacec5i2qdzl6initctpqpgsexvlmute7kscabhpguyfhitywlsdztzs
       
      - **proposal-cid**=bafyreicqnldytirq6xxaa2aazwcrzhqltrjb5zutwdp4x3fr6rkkzlh4du
      
      ```
      > Recv: 584.6 MiB, Paid 0 FIL, ClientEventAllBlocksReceived (DealStatusCompleted)
     [ec2-user@ip-172-31-20-161 lotus]$ lotus client retrieve --miner f0127896 
     bafykbzacec5i2qdzl6initctpqpgsexvlmute7kscabhpguyfhitywlsdztzs /dev/null
      ```
---    
- [x] Old client does an offline storage deal with an old miner -> client upgrades and then we do a retrieval.

    ```
    > Recv: 584.6 MiB, Paid 0 FIL, ClientEventBlockstoreFinalized (DealStatusCompleted)
    Success
     $ lotus client retrieve --miner f0127896 
     bafykbzacec5i2qdzl6initctpqpgsexvlmute7kscabhpguyfhitywlsdztzs /dev/null
    ```
---
#### Additional non-blocking tests to run 

- [x] Client does storage deal with upgrader Miner -> Miner downgrades. We do a retrieval.

   ```
   > Recv: 584.6 MiB, Paid 0 FIL, ClientEventBlockstoreFinalized (DealStatusCompleted)
  Success
  [ec2-user@ip-172-31-20-161 filc]$ lotus client retrieve --miner f0127896 
  bafykbzacebwuo3xhd2yhwmphg35npcxfrfzigg4qd2dytcxuyuhbp5eo4scbw /dev/null
   ```

- [ ] Client does a storage deal with an upgraded Miner -> Miner downgrades and removes the `dagstore` repo. Miner upgrades again and we do a retrieval.

---

**Comment by aarshkshah1992** [comment]
cc @jacobheun @raulk @dirkmc @nonsense .

**Comment by raulk** [comment]
Merged in #6671.
