### ISSUE TITLE
Automate Stage 1 testing in Lotus release process

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/lotus#6875]
we need upgrade nodes for internal infra and add pass the checks listed in our release process, for example this list: #6270

### Stage 1 - Internal Testing

 - **Binaries:**
 
- [ ] Ensure the RC release has downloadable binaries
- [ ] Validate the binary is able to run on at least one platform

- **Upgrade our testnet infra**

- [ ] 1 bootstrap node
- [ ]  1 miner
- [ ]  Scratch nodes
- [ ]  Wait 24 hours, confirm nodes stay in sync
- [ ]  Remaining testnet infra

- **Upgrade our mainnet infra**
 
- [ ] Subset of development full archival nodes
- [ ]  Subset of bootstrappers (1 per region)
- [ ]  Confirm nodes stay in sync

- **Metrics report**
- [ ] Block validation time
- [ ] Memory / CPU usage
- [ ] Number of goroutines
- [ ] IPLD block read latency
- [ ] Bandwidth usage

 If anything has worsened significantly, investigate + fix
Confirm the following work (some combination of Testground / Calibnet / Mainnet / beta users)
- [ ] Seal a sector
- [ ]  make a deal
- [ ]  Submit a PoSt
- [ ]  (optional) let a sector go faulty, and see it be recovered

**Comment by BlocksOnAChain** [comment]
not working on this, it included in https://github.com/filecoin-project/lotus/issues/6874

**Comment by BigLep** [comment]
@BlocksOnAChain : is this really a subset of https://github.com/filecoin-project/lotus/issues/6874 ?  I was seeing these as somewhat separate as this task is about getting deployments to happen automatically to certain hardware and that we have the metrics.  It's then separate for us to do the steps like a seal sector.  Ideally that part is automated too (https://github.com/filecoin-project/lotus/issues/6874 ), but it can happen manually and still benefit from the work in this issue.
