### ISSUE TITLE
Progress tracker needed

### ISSUE THREAD

**Issue by aaron3481** [filecoin-project/lotus#6884]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

lotus miner/worker - sealing

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

I'm always frustrated when trying to trace all tasks progress, especially when I have multiple worker machines. This is also a problem when I trying to schedule tasks evenly to each machines.

### Describe the solution you'd like

I'd like to add progress value when calling "lotus-miner sealing jobs" so that my monitor app can get trace of it.

**Comment by Reiers** [comment]
Hi @aaron3481 

Thank you the feature request. 

While it would be nice to have directly in Lotus - we do have tools made by the community that take care of this:
Checkout: https://github.com/s0nik42/lotus-farcaster
I think it has everything you are looking for.

Closing fr ticket.
