### ISSUE TITLE
Dedicated env var for lotus markets

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6935]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

Other

### Improvement Suggestion

Currently with a split markets process and to run a cmd, a process path must be identified like `LOTUS_MINER_PATH=~/markets-repo-location ./lotus-miner`

which means, miners need to provide this path specifically for each operation they are about to run.

ideally, we have dedicated evn var, for example, `LOTUS_MINER_X` and `LOTUS_MARKETS_X` for each process and will be read automatically according to the operation.
