### ISSUE TITLE
M1: miner with 2k deals but 0 migrated to dagstore

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#7017]
### Checklist

- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] I **am** reporting a bug w.r.t one of the [M1 tags](https://github.com/filecoin-project/lotus/discussions/6852#discussioncomment-1043951). If not, choose another issue option [here](https://github.com/filecoin-project/lotus/issues/new/choose).
- [X] I am **not** reporting a bug around deal making. If yes, create a [M1 Bug Report For Deal Making](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fbug%2CM1-release&template=m1_bug_report_deal.yml).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.

### Lotus component

Other

### Lotus Tag and  Version

```text
m1.3.4
```

### Describe the Bug

Miner has 2697 deals:

```
2021-08-11T00:46:06.057+0900	INFO	dagstore.migrator	dagstore/wrapper.go:286	registering shards for all active deals in sealing subsystem	\{"count": 2697\}\
```

However, the migrator reports a nil PieceCID for **all** deals:

```
2021-08-11T00:46:06.057+0900	WARN	dagstore.migrator	dagstore/wrapper.go:335	deal has nil piece CID; skipping	\{"deal_id": 2202633\}\
2021-08-11T00:46:06.058+0900	WARN	dagstore.migrator	dagstore/wrapper.go:335	deal has nil piece CID; skipping	\{"deal_id": 0\}\
2021-08-11T00:46:06.058+0900	WARN	dagstore.migrator	dagstore/wrapper.go:335	deal has nil piece CID; skipping	\{"deal_id": 0\}\
2021-08-11T00:46:06.058+0900	WARN	dagstore.migrator	dagstore/wrapper.go:335	deal has nil piece CID; skipping	\{"deal_id": 0\}\
2021-08-11T00:46:06.058+0900	WARN	dagstore.migrator	dagstore/wrapper.go:335	deal has nil piece CID; skipping	\{"deal_id": 0\}\
2021-08-11T00:46:06.058+0900	WARN	dagstore.migrator	dagstore/wrapper.go:335	deal has nil piece CID; skipping	\{"deal_id": 2252899\}\
2021-08-11T00:46:06.058+0900	WARN	dagstore.migrator	dagstore/wrapper.go:335	deal has nil piece CID; skipping	\{"deal_id": 0\}\
2021-08-11T00:46:06.058+0900	WARN	dagstore.migrator	dagstore/wrapper.go:335	deal has nil piece CID; skipping	\{"deal_id": 0\}\
2021-08-11T00:46:06.058+0900	WARN	dagstore.migrator	dagstore/wrapper.go:335	deal has nil piece CID; skipping	\{"deal_id": 0\}\
2021-08-11T00:46:06.058+0900	WARN	dagstore.migrator	dagstore/wrapper.go:335	deal has nil piece CID; skipping	\{"deal_id": 0\}\
2021-08-11T00:46:06.058+0900	WARN	dagstore.migrator	dagstore/wrapper.go:335	deal has nil piece CID; skipping	\{"deal_id": 0\}\
```

Leading to all deals being skipped on migration:

```
2021-08-11T00:46:06.095+0900	INFO	dagstore.migrator	dagstore/wrapper.go:361	finished registering all shards	\{"total": 0\}\
```

And a total of 0 deals migrated to the dagstore.

### Logging Information

```text
See above.
```

**Comment by raulk** [comment]
Fixed in https://github.com/filecoin-project/lotus/commit/d3cf5b0bc008a5f1681a5927f7eb8b94c89d70d7.
