### ISSUE TITLE
[meta issue] miner runtime architecture: next steps

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#7124]
This issue defines the next steps to consider for miner runtime improvements:

- [ ] Solving the environment variable mess in the CLI, potentially deprecating the many env vars + CLI flags, and moving to an explicit `lotus-cli.yml` config file (that could be auto-generated once from current env vars).
- [ ] Deciding whether we want or not a lotus-markets entrypoint — this has been requested by miners, but I personally think it’s a bad idea.
- [ ] Generally designing a service-oriented runtime environment for lotus-miner, that: (1) enables third parties to develop miner-side services, (2) structures dependencies across modules in a obvious, observable, and ordered/organized manner (e.g. with supervisor like trees), rather than incurring in spaghetti jumbles.
– [ ] 1:N markets — miners are already wanting this! This will enable horizontal scaling of deal-making, potentially orchestrating a farm of markets processes with k8s or the like, to scale elastically depending on real-time demand.

**Comment by jennijuju** [comment]
related https://github.com/filecoin-project/lotus/discussions/7170
