### ISSUE TITLE
Test FIP0029

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9370]
@TippyFlitsUK  could you please add the user testing we should check in this ticket.

(for cli. add to documentation as well)

**Comment by arajasek** [comment]
In addition to the manual testing @jennijuju describes, think an integ test in Lotus covering this behaviour would be a P3 nice-to-have test.

**Comment by jennijuju** [comment]
> In addition to the manual testing @jennijuju describes, think an integ test in Lotus covering this behaviour would be a P3 nice-to-have test.

Like happy path? Okie I will see if I can find some time to do it

**Comment by TippyFlitsUK** [comment]
PR introduced that we should test:
- [ ] miner info #9308, upon migration, the initial beneficiary address == owner address 
- [ ] try to withdraw the balance #9258 
- [ ] change beneficiary address #9254 
- [ ] withdraw the balance, happy case testing
- [ ] withdraw the balance exceeding the qouta
- [ ] try to withdraw the balance when the term is expired
- [ ] change the beneficiary address again

**Comment by TippyFlitsUK** [comment]
### FIP0029 Testing:

- 👍  - Beneficiary address is correctly set to the owner address and lotus-miner info displays this correctly.

- 👍  - lotus-miner actor withdraw works both with and without the new --beneficiary flag.

```
lotus-miner actor withdraw 150
Requested withdrawal in message bafy2bzaceb5syzeexj7rbunssonopzrflunxpue7w3kr7bud7hkiy3etmqmxs
waiting for it to be included in a block..
Successfully withdrew 150 FIL 
```

```
lotus-miner actor withdraw --beneficiary 150
Requested withdrawal in message bafy2bzacedyit5nppd4xyjooyqlkpaqnrfd3gsjy3o53jxzyg7o5ynv472cto
waiting for it to be included in a block..
Successfully withdrew 150 FIL
```

- ❗ Unable to propose beneficiary address change

```
lotus-miner actor propose-change-beneficiary --actor=t01017 --really-do-it t3wmvj7xqbthyjkcrsrtdiavgwxajugkwwxt5lhgiioyu7nyiuren3ltb77zndlyqkdiovdxtsfylw5gjti5sa 100 19250
ERROR: mpool push: GasEstimateMessageGas error: message execution failed: exit 24, reason: message failed with backtrace:
00: f01017 (method 30) -- failed to validate caller (24)
```

**Comment by TippyFlitsUK** [comment]
Updated: 

- 👍 - Beneficiary address is correctly set to the owner address and lotus-miner info displays this correctly.
- 👍 - `lotus-miner actor withdraw` works both with and without the new --beneficiary flag.
- 👍 - Changed and confirmed beneficiary successfully 👇.
```
Propose Message CID: bafy2bzacedys46za25wcg72fx5kvhesubtds4o3p3q7yjkk3sk3zkot4ppmpw
Beneficiary address change awaiting additional confirmations

Beneficiary:    t040347
Pending Beneficiary Term:
New Beneficiary:        t040350
New Quota:      100000000000000000000
New Expiration: 1407650
Approved By Beneficiary:        true
Approved By Nominee:    false

Confirming Pending Beneficiary Term of:
Beneficiary:  t040350
Quota: 100000000000000000000
Expiration Epoch: 1407650
Confirm Message CID: bafy2bzacea4tzr6algy2vst67usugea2gevxzeokil2mg3jly6bta3qqtvuki

Beneficiary:    t040350
Beneficiary Quota:      100000000000000000000
Beneficiary Used Quota: 0
Beneficiary Expiration: 1407650
```
-  👍 - Withdrew balance successfully 👇.
```
lotus-miner actor withdraw 10
Requested withdrawal in message bafy2bzacedfxks6ientctx5zintvo3u3hijbpjfjvp7ebtmdalw5lbcvfzdv2
waiting for it to be included in a block..
Successfully withdrew 10 FIL 

Beneficiary:    t040350
Beneficiary Quota:      100000000000000000000
Beneficiary Used Quota: 10000000000000000000
Beneficiary Expiration: 1407650
```
-  👍 - Attempted to withdraw balance in excess of quota. Remaining quota was withdrawn and excess amount was not.👇.
```
lotus-miner actor withdraw 150
Requested withdrawal in message bafy2bzaced4zeja2d6fyshvvjeqw6hcx36hmlcshqpy6xcnx23fwf73iwboyy
waiting for it to be included in a block..
Successfully withdrew 90 FIL
```
- 👍 - Attempting withdrawal after term expiry failed 👇.
```
lotus-miner actor withdraw 55
ERROR: GasEstimateMessageGas error: message execution failed: exit 18, reason: message failed with backtrace:
00: f040349 (method 16) -- beneficiary expiration of epoch 1407650 passed or quota of 100.0 depleted with 0.0 used (18)
```

- 👍 - Changed and confirmed beneficiary for a second time 👇.
```
Propose Message CID: bafy2bzaceb6wp45kd7hpkmqgpac2h2eukor7gznr2fm4hfuiwzhrfhi76ufes
Beneficiary address change awaiting additional confirmations

Beneficiary:    t040350
Pending Beneficiary Term:
New Beneficiary:        t040351
New Quota:      100000000000000000000
New Expiration: 1407650
Approved By Beneficiary:        true
Approved By Nominee:    false

Confirming Pending Beneficiary Term of:
Beneficiary:  t040351
Quota: 100000000000000000000
Expiration Epoch: 1407650
Confirm Message CID: bafy2bzacebcnfji4grrnyiecdjshyfbmpzc5eixwnpagjfxgzu3wf4bghyepc

Beneficiary:    t040351
Beneficiary Quota:      100000000000000000000
Beneficiary Used Quota: 0
Beneficiary Expiration: 1407650
```
